In [13]:
import pandas as pd
from glob import glob
import numpy as np

pd.set_option("display.max_columns", None)  # Show all columns
pd.set_option("display.width", None)        # Use full width of the console
pd.set_option("display.max_colwidth", None)  # Show full content in each column

In [2]:
aggregate_sets = ["/home/csutter/DRIVE-clean/operational_runs/set1_20250924",
"/home/csutter/DRIVE-clean/operational_runs/set2_20250924",
"/home/csutter/DRIVE-clean/operational_runs/set3_20250924",
"/home/csutter/DRIVE-clean/operational_runs/set4_iceWTA_20250925",
"/home/csutter/DRIVE-clean/operational_runs/set5_iceWTA_20250925",
"/home/csutter/DRIVE-clean/operational_runs/set6_probSRsample_20250925",
"/home/csutter/DRIVE-clean/operational_runs/set7_probSRsample_20250926",]

# Aggregate lists of prediction files
- And basic counts/totals

In [3]:
# SCM

scm_finalpreds = []
scm_datetime = []

for set in aggregate_sets:
    filepath = glob(f"{set}/data_6_ensembling/*/*/*/*/*")
    # print(len(filepath))
    # print(filepath)
    # find datetime
    for f in filepath:
        i = f.rfind("/")
        filedate = f[i-13:i]
        scm_finalpreds.append(f)
        scm_datetime.append(filedate)

print("date time instances for which we have predictions")
print(len(scm_finalpreds))
print(len(scm_datetime))
print(len(np.unique(scm_datetime))) # if this is less than the full len, it just means some of the datetimes were ran in multiple sets. Not a big deal, just duplicate ran more than once

# jsut to grab the total of unique DATES ran
scm_dates = [i[0:8] for i in scm_datetime]
print("unique dates ran")
print(len(np.unique(scm_dates)))

# print some examples to see
print("examples")
print(scm_finalpreds[0:3])
print(scm_datetime[0:3])
print(scm_dates[0:3])

date time instances for which we have predictions
956
956
956
unique dates ran
90
examples
['/home/csutter/DRIVE-clean/operational_runs/set1_20250924/data_6_ensembling/2024/02/17/20240217_1800/finalpreds.csv', '/home/csutter/DRIVE-clean/operational_runs/set1_20250924/data_6_ensembling/2024/02/17/20240217_1300/finalpreds.csv', '/home/csutter/DRIVE-clean/operational_runs/set1_20250924/data_6_ensembling/2024/02/17/20240217_1400/finalpreds.csv']
['20240217_1800', '20240217_1300', '20240217_1400']
['20240217', '20240217', '20240217']

In [4]:
# ODM

odm_finalpreds = []
odm_datetime = []

for set in aggregate_sets:
    filepath = glob(f"{set}/data_odm_2_ensembling/*/*/*/*/*")
    # print(len(filepath))
    # print(filepath)
    # find datetime
    for f in filepath:
        i = f.rfind("/")
        filedate = f[i-13:i]
        odm_finalpreds.append(f)
        odm_datetime.append(filedate)

print("date time instances for which we have predictions")
print(len(odm_finalpreds))
print(len(odm_datetime))
print(len(np.unique(odm_datetime))) # if this is less than the full len, it just means some of the datetimes were ran in multiple sets. Not a big deal, just duplicate ran more than once

# jsut to grab the total of unique DATES ran
odm_dates = [i[0:8] for i in odm_datetime]
print("unique dates ran")
print(len(np.unique(odm_dates)))

# print some examples to see
print("examples")
print(odm_finalpreds[0:3])
print(odm_datetime[0:3])
print(odm_dates[0:3])

date time instances for which we have predictions
956
956
956
unique dates ran
90
examples
['/home/csutter/DRIVE-clean/operational_runs/set1_20250924/data_odm_2_ensembling/2024/02/17/20240217_1800/finalpreds.csv', '/home/csutter/DRIVE-clean/operational_runs/set1_20250924/data_odm_2_ensembling/2024/02/17/20240217_1300/finalpreds.csv', '/home/csutter/DRIVE-clean/operational_runs/set1_20250924/data_odm_2_ensembling/2024/02/17/20240217_1400/finalpreds.csv']
['20240217_1800', '20240217_1300', '20240217_1400']
['20240217', '20240217', '20240217']

# Find dates with most severe snow examples

In [15]:
exdf = pd.read_csv("/home/csutter/DRIVE-clean/operational_runs/set1_20250924/data_6_ensembling/2024/02/17/20240217_1800/finalpreds.csv")

exdf.head(3)

,Unnamed: 0,Unnamed: 0.2,Unnamed: 0.1,innerPhase_x,img_name,img_orig,site,img_cat,foldnum_x,timeofday,timeofevent,m0_calib_prob_dry,m0_calib_prob_poor_viz,m0_calib_prob_snow,m0_calib_prob_snow_severe,m0_calib_prob_wet,m0_calib_prob,img_orig_hrrr,innerPhase_y,foldnum_y,Latitude,Longitude,yr,mo,day,date,time,ymd,date_and_time_str,date_and_time_dt,date_and_time_dt_round,date_and_time_dt_init,init_hr,init_year,init_month,init_day,init_yyyymmdd,hrrr_file,HRRR_latlon,HRRR_distkm,time.1,valid_time,latitude,longitude,t2m,pt,sh2,d2m,r2,u10,v10,si10,asnow,tp,orog,cape,mslma,dswrf,dlwrf,tcc,gh,dpt,atmosphere,isobaricInhPa,uavg,o_prob_dry,o_prob_poor_viz,o_prob_snow,o_prob_snow_severe,o_prob_wet,o_pred,o_prob,classifier_TF,classifier_01,o_prob_calib,m0_calib_pred,m1_calib_prob_wet,m1_calib_prob_dry,m1_calib_prob_snow,m1_calib_prob_snow_severe,m1_calib_prob_poor_viz,m1_calib_prob,m1_calib_pred,m2_calib_prob_wet,m2_calib_prob_dry,m2_calib_prob_snow,m2_calib_prob_snow_severe,m2_calib_prob_poor_viz,m2_calib_prob,m2_calib_pred,m3_calib_prob_wet,m3_calib_prob_dry,m3_calib_prob_snow,m3_calib_prob_snow_severe,m3_calib_prob_poor_viz,m3_calib_prob,m3_calib_pred,m4_calib_prob_wet,m4_calib_prob_dry,m4_calib_prob_snow,m4_calib_prob_snow_severe,m4_calib_prob_poor_viz,m4_calib_prob,m4_calib_pred,list_5preds,list_5probs,dict_catAsKeys_modelAsValues,dict_catAsKeys_countAsValues,dict_catAsKeys_probsAsValues,dict_mostConfident_singleModel,ensembleAvg_dry,ensembleAvg_snow,ensembleAvg_snow_severe,ensembleAvg_wet,ensembleAvg_poor_viz,ensembleAvg_pred,ensembleAvg_predprob,ensembleMode_pred,ensembleMaxConf_pred,methodalign_1_2,methodalign_1_3,methodalign_2_3,select,decision,select_correct,ok_select,num_models_pred_cat,conf_consist,conf_probability,conf_overall,confidence
0,0,2105,2105,innerTrain,001_9T_(MM_002.00)_WB_E_of_Hackey_Brdg__Westbound__TRAFFICLAND_6427_2024-02-17-18:01:15.jpg,/home/csutter/cron/data/TRAFFICLAND_6427/20240217/001_9T_(MM_002.00)_WB_E_of_Hackey_Brdg__Westbound__TRAFFICLAND_6427_2024-02-17-18:01:15.jpg,TRAFFICLAND_6427,dry,0,day,"{Timestamp('2024-02-17 11:19:59.724745'): 'dawn', Timestamp('2024-02-17 11:48:30.340348'): 'sunrise', Timestamp('2024-02-17 22:32:51.153503'): 'sunset', Timestamp('2024-02-17 23:01:23.243334'): 'dusk'}",0.850543,0.017317,0.031435,0.025875,0.07483,0.850543,/home/csutter/cron/data/TRAFFICLAND_6427/20240217/001_9T_(MM_002.00)_WB_E_of_Hackey_Brdg__Westbound__TRAFFICLAND_6427_2024-02-17-18:01:15.jpg,innerTrain,0,40.732063,-74.094898,2024,2,17,20240217,18:01:15,20240217,18:01:15 20240217,2024-02-17 18:01:15,2024-02-17 18:00:00,2024-02-17 16:00:00,16,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t16z_02.parquet,"[40.73058990877996, -74.09561734113817]",0.174507,2024-02-17 16:00:00,2024-02-17 18:00:00,40.73059,-74.095617,274.81683,274.4486,0.00282,269.14084,66.6,4.513753,-2.691334,5.200628,0.0,0.0,7.85714,90.0,100629.0,346.3,291.7,100.0,5230.795,222.0152,0.0,500.0,5.255211,0.826669,0.020083,0.036456,0.030008,0.086783,dry,0.826669,True,1,0.850543,dry,0.051757,0.892754,0.006602,0.00977,0.039117,0.892754,dry,0.216904,0.503597,0.061566,0.075077,0.142856,0.503597,dry,0.153828,0.375,0.113586,0.146014,0.211572,0.375,dry,0.156244,0.524229,0.083348,0.093512,0.142666,0.524229,dry,"['dry', 'dry', 'dry', 'dry', 'dry']","[0.8505434782608695, 0.8927536231884058, 0.5035971223021583, 0.375, 0.5242290748898678]","{'dry': ['m0', 'm1', 'm2', 'm3', 'm4']}",{'dry': 5},{'dry': 0.6292246597282602},{'dry': 0.8927536231884058},0.629225,0.059307,0.07005,0.130713,0.110706,dry,0.629225,dry,dry,True,True,True,dry,align_avg_mode,True,True,5,3,2,2.5,high
1,1,1050,1050,innerTrain,001_9T_(MM_002.74)_EB_at_Duncan_Ave__Eastbound__TRAFFICLAND_6437_2024-02-17-18:01:25.jpg,/home/csutter/cron/data/TRAFFICLAND_6437/20240217/001_9T_(MM_002.74)_EB_at_Duncan_Ave__Eastbound__TRAFFICLAND_6437_2024-02-17-18:01:25.jpg,TRAFFICLAND_6437,dry,0,day,"{Timestamp('2024-02-17 11:19:57.298875'): 'dawn', Timestamp('2024-02-17 11:48:27.874740'): 'sunrise', Timestamp('2024-02-17 22:32:48.941078'): 'sunset', Timestamp('2024-02-17 23:01:20.991025'): 'dusk'}",0.850543,0.017317,0.031435,0.025875,0.07483,0.850543,/home/csutter/cron/data/TRAFFICLAND_6437/20240217/001_9T_(MM_002.74)_EB_at_Duncan_Ave__Eastbound__TRAFFICLAND_6437_2024-02-17-18:01:25.jpg,innerTrain,0,40.730568,-74.085155,2024,2,17,20240217,18:01:25,20240217,18:01:25 20240217,2024-02-17 18:01:25,2024-02-17 18:00:00,2024-02-17 16:00:00,16,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t16z_02.parquet,"[40.73058990877996, -74.09561734113817]",0.883829,2024-02-17 16:00:00,2024-02-17 18:00:00,40.73059,-74.095617,274.81683,274.4486,0.00282,269.14084,66.6,4.513753,-2.691334,5.200628,0.0,0.0,7.85714,90.0,100629.0,346.3,291.7,100.0,5230.795,222.0152,0.0,500.0,5.255211,0.826669,0.020083,0.036456,0.030008,0.086783,dry,0.826669,True,1,0.850543,dry,0.051757,0.892754,0.006602,0.00977,0.039117,0.892754,dry,0.216904,0.503597,0.061566,0.075077,0.142856,0.503597,dry,0.153828,0.375,0.113586,0.146014,0.211572,0.375,dry,0.156244,0.524229,0.083348,0.093512,0.142666,0.524229,dry,"['dry', 'dry', 'dry', 'dry', 'dry']","[0.8505434782608695, 0.8927536231884058, 0.5035971223021583, 0.375, 0.5242290748898678]","{'dry': ['m0', 'm1', 'm2', 'm3', 'm4']}",{'dry': 5},{'dry': 0.6292246597282602},{'dry': 0.8927536231884058},0.629225,0.059307,0.07005,0.130713,0.110706,dry,0.629225,dry,dry,True,True,True,dry,align_avg_mode,True,True,5,3,2,2.5,high
2,2,118,118,innerTrain,001_9T_(MM_003.10)_WB_at_Sip_Ave__Westbound__TRAFFICLAND_6434_2024-02-17-18:01:24.jpg,/home/csutter/cron/data/TRAFFICLAND_6434/20240217/001_9T_(MM_003.10)_WB_at_Sip_Ave__Westbound__TRAFFICLAND_6434_2024-02-17-18:01:24.jpg,TRAFFICLAND_6434,dry,0,day,"{Timestamp('2024-02-17 11:19:56.575438'): 'dawn', Timestamp('2024-02-17 11:48:27.257341'): 'sunrise', Timestamp('2024-02-17 22:32:47.637129'): 'sunset', Timestamp('2024-02-17 23:01:19.793499'): 'dusk'}",0.850543,0.017317,0.031435,0.025875,0.07483,0.850543,/home/csutter/cron/data/TRAFFICLAND_6434/20240217/001_9T_(MM_003.10)_WB_at_Sip_Ave__Westbound__TRAFFICLAND_6434_2024-02-17-18:01:24.jpg,innerTrain,0,40.734547,-74.081143,2024,2,17,20240217,18:01:24,20240217,18:01:24 20240217,2024-02-17 18:01:24,2024-02-17 18:00:00,2024-02-17 16:00:00,16,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t16z_02.parquet,"[40.73058990877996, -74.09561734113817]",1.299276,2024-02-17 16:00:00,2024-02-17 18:00:00,40.73059,-74.095617,274.81683,274.4486,0.00282,269.14084,66.6,4.513753,-2.691334,5.200628,0.0,0.0,7.85714,90.0,100629.0,346.3,291.7,100.0,5230.795,222.0152,0.0,500.0,5.255211,0.826669,0.020083,0.036456,0.030008,0.086783,dry,0.826669,True,1,0.850543,dry,0.051757,0.892754,0.006602,0.00977,0.039117,0.892754,dry,0.216904,0.503597,0.061566,0.075077,0.142856,0.503597,dry,0.153828,0.375,0.113586,0.146014,0.211572,0.375,dry,0.156244,0.524229,0.083348,0.093512,0.142666,0.524229,dry,"['dry', 'dry', 'dry', 'dry', 'dry']","[0.8505434782608695, 0.8927536231884058, 0.5035971223021583, 0.375, 0.5242290748898678]","{'dry': ['m0', 'm1', 'm2', 'm3', 'm4']}",{'dry': 5},{'dry': 0.6292246597282602},{'dry': 0.8927536231884058},0.629225,0.059307,0.07005,0.130713,0.110706,dry,0.629225,dry,dry,True,True,True,dry,align_avg_mode,True,True,5,3,2,2.5,high

In [14]:
exdf.columns

Index(['Unnamed: 0', 'Unnamed: 0.2', 'Unnamed: 0.1', 'innerPhase_x',
       'img_name', 'img_orig', 'site', 'img_cat', 'foldnum_x', 'timeofday',
       ...
       'methodalign_2_3', 'select', 'decision', 'select_correct', 'ok_select',
       'num_models_pred_cat', 'conf_consist', 'conf_probability',
       'conf_overall', 'confidence'],
      dtype='object', length=131)

In [57]:
odmex = pd.read_csv('/home/csutter/DRIVE-clean/operational_runs/set1_20250924/data_odm_2_ensembling/2024/02/17/20240217_1400/finalpreds.csv')

display(odmex.head(3))

print(odmex.columns)

,Unnamed: 0,Unnamed: 0.1,img_orig,site,img_cat,img_name,innerPhase,foldnum,Latitude,Longitude,...,methodalign_2_3,select,decision,select_correct,ok_select,num_models_pred_cat,conf_consist,conf_probability,conf_overall,confidence
0,0,2110,/home/csutter/cron/data/TRAFFICLAND_6427/20240...,TRAFFICLAND_6427,dry,001_9T_(MM_002.00)_WB_E_of_Hackey_Brdg__Westbo...,innerTrain,0,40.732063,-74.094898,...,True,obs,align_avg_mode,False,False,4,3,3,3.0,high
1,1,1052,/home/csutter/cron/data/TRAFFICLAND_6437/20240...,TRAFFICLAND_6437,dry,001_9T_(MM_002.74)_EB_at_Duncan_Ave__Eastbound...,innerTrain,0,40.730568,-74.085155,...,True,obs,align_avg_mode,False,False,4,3,3,3.0,high
2,2,119,/home/csutter/cron/data/TRAFFICLAND_6434/20240...,TRAFFICLAND_6434,dry,001_9T_(MM_003.10)_WB_at_Sip_Ave__Westbound__T...,innerTrain,0,40.734547,-74.081143,...,True,obs,align_avg_mode,False,False,4,3,3,3.0,high

Index(['Unnamed: 0', 'Unnamed: 0.1', 'img_orig', 'site', 'img_cat', 'img_name',
       'innerPhase', 'foldnum', 'Latitude', 'Longitude', 'dt_str',
       'timeofevent', 'timeofday', 'm0_prob_nonobs', 'm0_prob_obs',
       'm0_model_pred', 'tracker', 'm0_model_prob', 'm1_prob_nonobs',
       'm1_prob_obs', 'm1_model_prob', 'm1_model_pred', 'm2_prob_nonobs',
       'm2_prob_obs', 'm2_model_prob', 'm2_model_pred', 'm3_prob_nonobs',
       'm3_prob_obs', 'm3_model_prob', 'm3_model_pred', 'list_5preds',
       'list_5probs', 'dict_catAsKeys_modelAsValues',
       'dict_catAsKeys_countAsValues', 'dict_catAsKeys_probsAsValues',
       'dict_mostConfident_singleModel', 'ensembleAvg_obs',
       'ensembleAvg_nonobs', 'ensembleAvg_pred', 'ensembleAvg_predprob',
       'ensembleMode_pred', 'ensembleMaxConf_pred', 'methodalign_1_2',
       'methodalign_1_3', 'methodalign_2_3', 'select', 'decision',
       'select_correct', 'ok_select', 'num_models_pred_cat', 'conf_consist',
       'conf_probability', 'conf_overall', 'confidence'],
      dtype='object')

In [6]:
# Organize SCM and ODM together

scm_catlist = ["dry", "poor_viz","snow","snow_severe","wet"]
scm_filelist = []
scm_catcount = [] # each list entry has order of dry, poor_viz, etc

odm_catlist = ["nonobs","obs"]
odm_filelist = []
odm_catcount = [] # each list entry has order of dry, poor_viz, etc

dateinstance = []

def count_cat(dfinput, catinput):
    df2 = dfinput[dfinput["select"]==catinput]
    return len(df2)

for i in range(0,len(scm_finalpreds)): #len(scm_finalpreds)
    # grab corresponding date st we can find it in ODM list
    dt = scm_datetime[i]
    try: # this way if the time doesnt exist in ODM, we can skip this instance
        odm_index = odm_datetime.index(dt)
    except:
        continue # this continue immediately stops the code from running more below, and moves on to next iteration in loop. Key thing with continue is that it doesn't run the rest of the code below. Benefit of this is that it isolates the "try" command. For example if we lumped ALL code under try (and therefore wouldn need the continue line), we wouldnt be able to isolate for what reason the try didn't work. Since now it's only trying to find the odm index, we know exactly what try failed. 

    # grab file names for SCM and ODM, will have both (see the try/except above)
    scmfile = scm_finalpreds[i]
    odmfile = odm_finalpreds[odm_index]

    scmdf = pd.read_csv(scmfile)
    odmdf = pd.read_csv(odmfile)
    # display(odmdf)
    # grab scm cat counts and append
    scm_catcount_instance = []
    for cat in scm_catlist:
        ct = count_cat(scmdf, cat)
        scm_catcount_instance.append(ct)
    scm_filelist.append(scmfile)
    scm_catcount.append(scm_catcount_instance) # append list from instance to outer list

    # grab odm cat counts and append
    odm_catcount_instance = []
    for cat in odm_catlist:
        ct = count_cat(odmdf, cat)
        odm_catcount_instance.append(ct)
    odm_filelist.append(odmfile)
    odm_catcount.append(odm_catcount_instance) # append list from instance to outer list

    dateinstance.append(dt) # put at  end bc want the code to have ran before adding this date as successul for tracking


# print(scm_filelist)
# print(scm_catcount)
# print(odm_filelist)
# print(odm_catcount)
# print(dateinstance)


df_countall_scm = pd.DataFrame(scm_catcount, columns=scm_catlist)
df_countall_scm["scm_run"] = scm_filelist

df_countall_odm = pd.DataFrame(odm_catcount, columns=odm_catlist)
df_countall_odm["odm_run"] = odm_filelist

print(len(df_countall_scm),len(df_countall_odm))

df_all = pd.concat([df_countall_scm,df_countall_odm], axis = 1) # concat cols side by side
print(len(df_all))

df_all["datetime"] = dateinstance
display(df_all.head(4))

956 956
956

,dry,poor_viz,snow,snow_severe,wet,scm_run,nonobs,obs,odm_run,datetime
0,1799,8,82,8,469,/home/csutter/DRIVE-clean/operational_runs/set...,1371,1000,/home/csutter/DRIVE-clean/operational_runs/set...,20240217_1800
1,95,45,1248,12,966,/home/csutter/DRIVE-clean/operational_runs/set...,1359,1012,/home/csutter/DRIVE-clean/operational_runs/set...,20240217_1300
2,133,78,1079,10,1066,/home/csutter/DRIVE-clean/operational_runs/set...,1354,1017,/home/csutter/DRIVE-clean/operational_runs/set...,20240217_1400
3,2247,13,28,0,78,/home/csutter/DRIVE-clean/operational_runs/set...,1332,1039,/home/csutter/DRIVE-clean/operational_runs/set...,20240217_0200

In [ ]:
df_all.to_csv("")

In [10]:
sort_sevsnow = df_all.sort_values(["snow_severe"], ascending = False)
sort_sevsnow

,dry,poor_viz,snow,snow_severe,wet,scm_run,nonobs,obs,odm_run,datetime
898,105,12,1011,1058,180,/home/csutter/DRIVE-clean/operational_runs/set...,1753,618,/home/csutter/DRIVE-clean/operational_runs/set...,20220129_1300
901,72,4,1122,972,196,/home/csutter/DRIVE-clean/operational_runs/set...,1757,614,/home/csutter/DRIVE-clean/operational_runs/set...,20220129_1600
897,93,4,1112,904,253,/home/csutter/DRIVE-clean/operational_runs/set...,1787,584,/home/csutter/DRIVE-clean/operational_runs/set...,20220129_1800
612,12,105,801,603,845,/home/csutter/DRIVE-clean/operational_runs/set...,1718,653,/home/csutter/DRIVE-clean/operational_runs/set...,20220225_1000
615,3,116,691,565,991,/home/csutter/DRIVE-clean/operational_runs/set...,1627,744,/home/csutter/DRIVE-clean/operational_runs/set...,20220225_1100
...,...,...,...,...,...,...,...,...,...,...
540,2331,2,5,0,28,/home/csutter/DRIVE-clean/operational_runs/set...,1270,1101,/home/csutter/DRIVE-clean/operational_runs/set...,20240301_0800
541,2304,2,31,0,29,/home/csutter/DRIVE-clean/operational_runs/set...,1285,1086,/home/csutter/DRIVE-clean/operational_runs/set...,20240301_0400
206,2306,17,3,0,40,/home/csutter/DRIVE-clean/operational_runs/set...,1264,1107,/home/csutter/DRIVE-clean/operational_runs/set...,20231212_0400
207,2319,24,4,0,19,/home/csutter/DRIVE-clean/operational_runs/set...,1277,1094,/home/csutter/DRIVE-clean/operational_runs/set...,20231212_0300
415,2309,32,11,0,14,/home/csutter/DRIVE-clean/operational_runs/set...,1095,1276,/home/csutter/DRIVE-clean/operational_runs/set...,20231207_0400

# Marry the two model dfs at the prediction-level, to parse out paired prediction of 5cat|ynobs

In [ ]:
# Organize SCM and ODM together

scm_catlist = ["dry", "poor_viz","snow","snow_severe","wet"]
scm_filelist = []
scm_catcount = [] # each list entry has order of dry, poor_viz, etc

odm_catlist = ["nonobs","obs"]
odm_filelist = []
odm_catcount = [] # each list entry has order of dry, poor_viz, etc

dateinstance = []

def count_cat(dfinput, catinput):
    df2 = dfinput[dfinput["select"]==catinput]
    return len(df2)

for i in range(0,len(scm_finalpreds)): #len(scm_finalpreds)
    # grab corresponding date st we can find it in ODM list
    dt = scm_datetime[i]
    try: # this way if the time doesnt exist in ODM, we can skip this instance
        odm_index = odm_datetime.index(dt)
    except:
        continue # this continue immediately stops the code from running more below, and moves on to next iteration in loop. Key thing with continue is that it doesn't run the rest of the code below. Benefit of this is that it isolates the "try" command. For example if we lumped ALL code under try (and therefore wouldn need the continue line), we wouldnt be able to isolate for what reason the try didn't work. Since now it's only trying to find the odm index, we know exactly what try failed. 

    # grab file names for SCM and ODM, will have both (see the try/except above)
    scmfile = scm_finalpreds[i]
    odmfile = odm_finalpreds[odm_index]

    scmdf = pd.read_csv(scmfile)
    odmdf = pd.read_csv(odmfile)

    merged = scmdf.merge(odmdf, how = "inner", on = "img_orig")

    # display(odmdf)
    # grab scm cat counts and append
    scm_catcount_instance = []
    for cat in scm_catlist:
        ct = count_cat(scmdf, cat)
        scm_catcount_instance.append(ct)
    scm_filelist.append(scmfile)
    scm_catcount.append(scm_catcount_instance) # append list from instance to outer list

    # grab odm cat counts and append
    odm_catcount_instance = []
    for cat in odm_catlist:
        ct = count_cat(odmdf, cat)
        odm_catcount_instance.append(ct)
    odm_filelist.append(odmfile)
    odm_catcount.append(odm_catcount_instance) # append list from instance to outer list

    dateinstance.append(dt) # put at  end bc want the code to have ran before adding this date as successul for tracking


# print(scm_filelist)
# print(scm_catcount)
# print(odm_filelist)
# print(odm_catcount)
# print(dateinstance)


df_countall_scm = pd.DataFrame(scm_catcount, columns=scm_catlist)
df_countall_scm["scm_run"] = scm_filelist

df_countall_odm = pd.DataFrame(odm_catcount, columns=odm_catlist)
df_countall_odm["odm_run"] = odm_filelist

print(len(df_countall_scm),len(df_countall_odm))

df_all = pd.concat([df_countall_scm,df_countall_odm], axis = 1) # concat cols side by side
print(len(df_all))

df_all["datetime"] = dateinstance
display(df_all.head(4))

# Save out copies of all final preds in one directory; doing this for two reasons:
1. Want it all organized for each access for API/dashboard, rather than the API needing to sift through file / dir structures. Although may end up adjusting this stuff
2. Miscellaneous reasons: small issues in ensembling code
    - needed to add select_prob col. That code has since been added to the scripts, so Won't need to run for any sets AFTER set7. But see notes below about this below:
        - For inferenc_run sets 1 through 7, Didnt have the selected cat probability col in the ensemble df - need to add select_prob col
        - But need to have it bc there are a few <1% of cases where the final cat "select" col does not align with ensembleavg method. Thus cant just rely on ensembleAvg_predprob
        - But at the time of many of the inference run sets, did not have that code in /home/csutter/DRIVE-clean/operational_inference/inference_ensemble.py and /home/csutter/DRIVE-clean/ensembling/scripts/nested_ensemble.py
        - As ad hoc fix, read in all the inference runs and 
    - low confidence should have been <=1.5 not <1, bc the min is 1, and that forced even the lowest confidence into medium. Fix this! See inference_ensemble.py for more info and https://docs.google.com/spreadsheets/d/1cnNLpkQ-XFYmPvYEwAh67HFW1mgloYDjSHmKpe0wV08/edit?gid=0#gid=0

In [26]:
### Fix confidence issue (see note above)
def confidence_qual(row):
    overall = row["conf_overall"]
    if overall <= 1.5: # three ways this can happen
        conf = "low"
    elif overall == 2: # three ways this can happen
        conf = "medium"
    elif overall >= 2.5: # three ways this can happen
        conf = "high"
    else:
        conf = "issue_confidence"
    return conf

### Add select_prob (see note above)
def selectprob(row): # note that this is in nested_ensemble as of 9/26, so will be autoomatically applied after set 7
    pred = row["select"]
    grabprob = row[f"ensembleAvg_{pred}"]
    return grabprob

#### RUN these new functions and save out into new organized dir! Dont want to lose original work though in case something goes awry with this. 

for f in scm_finalpreds[2:3]:
    d = pd.read_csv(f)
    d["select_prob"] =  d.apply(selectprob, axis=1)
    display(d.head(3))

    d["confidence"] = d.apply(confidence_qual, axis = 1)
    display(d.head(3))

,Unnamed: 0,Unnamed: 0.2,Unnamed: 0.1,innerPhase_x,img_name,img_orig,site,img_cat,foldnum_x,timeofday,timeofevent,m0_calib_prob_dry,m0_calib_prob_poor_viz,m0_calib_prob_snow,m0_calib_prob_snow_severe,m0_calib_prob_wet,m0_calib_prob,img_orig_hrrr,innerPhase_y,foldnum_y,Latitude,Longitude,yr,mo,day,date,time,ymd,date_and_time_str,date_and_time_dt,date_and_time_dt_round,date_and_time_dt_init,init_hr,init_year,init_month,init_day,init_yyyymmdd,hrrr_file,HRRR_latlon,HRRR_distkm,time.1,valid_time,latitude,longitude,t2m,pt,sh2,d2m,r2,u10,v10,si10,asnow,tp,orog,cape,mslma,dswrf,dlwrf,tcc,gh,dpt,atmosphere,isobaricInhPa,uavg,o_prob_dry,o_prob_poor_viz,o_prob_snow,o_prob_snow_severe,o_prob_wet,o_pred,o_prob,classifier_TF,classifier_01,o_prob_calib,m0_calib_pred,m1_calib_prob_wet,m1_calib_prob_dry,m1_calib_prob_snow,m1_calib_prob_snow_severe,m1_calib_prob_poor_viz,m1_calib_prob,m1_calib_pred,m2_calib_prob_wet,m2_calib_prob_dry,m2_calib_prob_snow,m2_calib_prob_snow_severe,m2_calib_prob_poor_viz,m2_calib_prob,m2_calib_pred,m3_calib_prob_wet,m3_calib_prob_dry,m3_calib_prob_snow,m3_calib_prob_snow_severe,m3_calib_prob_poor_viz,m3_calib_prob,m3_calib_pred,m4_calib_prob_wet,m4_calib_prob_dry,m4_calib_prob_snow,m4_calib_prob_snow_severe,m4_calib_prob_poor_viz,m4_calib_prob,m4_calib_pred,list_5preds,list_5probs,dict_catAsKeys_modelAsValues,dict_catAsKeys_countAsValues,dict_catAsKeys_probsAsValues,dict_mostConfident_singleModel,ensembleAvg_dry,ensembleAvg_snow,ensembleAvg_snow_severe,ensembleAvg_wet,ensembleAvg_poor_viz,ensembleAvg_pred,ensembleAvg_predprob,ensembleMode_pred,ensembleMaxConf_pred,methodalign_1_2,methodalign_1_3,methodalign_2_3,select,decision,select_correct,ok_select,num_models_pred_cat,conf_consist,conf_probability,conf_overall,confidence,select_prob
0,0,2105,2105,innerTrain,001_9T_(MM_002.00)_WB_E_of_Hackey_Brdg__Westbound__TRAFFICLAND_6427_2024-02-17-14:01:14.jpg,/home/csutter/cron/data/TRAFFICLAND_6427/20240217/001_9T_(MM_002.00)_WB_E_of_Hackey_Brdg__Westbound__TRAFFICLAND_6427_2024-02-17-14:01:14.jpg,TRAFFICLAND_6427,dry,0,day,"{Timestamp('2024-02-17 11:19:59.724745'): 'dawn', Timestamp('2024-02-17 11:48:30.340348'): 'sunrise', Timestamp('2024-02-17 22:32:51.153503'): 'sunset', Timestamp('2024-02-17 23:01:23.243334'): 'dusk'}",0.042088,0.076546,0.613636,0.133247,0.134484,0.613636,/home/csutter/cron/data/TRAFFICLAND_6427/20240217/001_9T_(MM_002.00)_WB_E_of_Hackey_Brdg__Westbound__TRAFFICLAND_6427_2024-02-17-14:01:14.jpg,innerTrain,0,40.732063,-74.094898,2024,2,17,20240217,14:01:14,20240217,14:01:14 20240217,2024-02-17 14:01:14,2024-02-17 14:00:00,2024-02-17 12:00:00,12,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t12z_02.parquet,"[40.73058990877996, -74.09561734113817]",0.174507,2024-02-17 12:00:00,2024-02-17 14:00:00,40.73059,-74.095617,272.47552,271.97363,0.00341,271.74094,95.3,-0.226598,-1.400036,1.553209,0.004438,0.433,7.85714,0.0,100792.0,241.0,280.1,100.0,5286.1255,220.63715,0.0,500.0,1.418255,0.048368,0.087969,0.555981,0.153131,0.154552,snow,0.555981,False,0,0.613636,snow,0.170797,0.060457,0.515464,0.085236,0.168047,0.515464,snow,0.321429,0.05764,0.162454,0.161124,0.297354,0.321429,wet,0.393162,0.013316,0.207839,0.134361,0.251322,0.393162,wet,0.242422,0.04558,0.333333,0.127001,0.251664,0.333333,snow,"['snow', 'snow', 'wet', 'wet', 'snow']","[0.6136363636363636, 0.5154639175257734, 0.3214285714285714, 0.3931623931623931, 0.3333333333333333]","{'snow': ['m0', 'm1', 'm4'], 'wet': ['m2', 'm3']}","{'snow': 3, 'wet': 2}","{'snow': 0.48747787149849003, 'wet': 0.35729548229548225}",{'snow': 0.6136363636363636},0.043816,0.366545,0.128194,0.252459,0.208987,snow,0.366545,snow,snow,True,True,True,snow,align_avg_mode,False,False,3,1,1,1.0,medium,0.366545
1,1,1050,1050,innerTrain,001_9T_(MM_002.74)_EB_at_Duncan_Ave__Eastbound__TRAFFICLAND_6437_2024-02-17-14:01:15.jpg,/home/csutter/cron/data/TRAFFICLAND_6437/20240217/001_9T_(MM_002.74)_EB_at_Duncan_Ave__Eastbound__TRAFFICLAND_6437_2024-02-17-14:01:15.jpg,TRAFFICLAND_6437,dry,0,day,"{Timestamp('2024-02-17 11:19:57.298875'): 'dawn', Timestamp('2024-02-17 11:48:27.874740'): 'sunrise', Timestamp('2024-02-17 22:32:48.941078'): 'sunset', Timestamp('2024-02-17 23:01:20.991025'): 'dusk'}",0.042088,0.076546,0.613636,0.133247,0.134484,0.613636,/home/csutter/cron/data/TRAFFICLAND_6437/20240217/001_9T_(MM_002.74)_EB_at_Duncan_Ave__Eastbound__TRAFFICLAND_6437_2024-02-17-14:01:15.jpg,innerTrain,0,40.730568,-74.085155,2024,2,17,20240217,14:01:15,20240217,14:01:15 20240217,2024-02-17 14:01:15,2024-02-17 14:00:00,2024-02-17 12:00:00,12,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t12z_02.parquet,"[40.73058990877996, -74.09561734113817]",0.883829,2024-02-17 12:00:00,2024-02-17 14:00:00,40.73059,-74.095617,272.47552,271.97363,0.00341,271.74094,95.3,-0.226598,-1.400036,1.553209,0.004438,0.433,7.85714,0.0,100792.0,241.0,280.1,100.0,5286.1255,220.63715,0.0,500.0,1.418255,0.048368,0.087969,0.555981,0.153131,0.154552,snow,0.555981,False,0,0.613636,snow,0.170797,0.060457,0.515464,0.085236,0.168047,0.515464,snow,0.321429,0.05764,0.162454,0.161124,0.297354,0.321429,wet,0.393162,0.013316,0.207839,0.134361,0.251322,0.393162,wet,0.242422,0.04558,0.333333,0.127001,0.251664,0.333333,snow,"['snow', 'snow', 'wet', 'wet', 'snow']","[0.6136363636363636, 0.5154639175257734, 0.3214285714285714, 0.3931623931623931, 0.3333333333333333]","{'snow': ['m0', 'm1', 'm4'], 'wet': ['m2', 'm3']}","{'snow': 3, 'wet': 2}","{'snow': 0.48747787149849003, 'wet': 0.35729548229548225}",{'snow': 0.6136363636363636},0.043816,0.366545,0.128194,0.252459,0.208987,snow,0.366545,snow,snow,True,True,True,snow,align_avg_mode,False,False,3,1,1,1.0,medium,0.366545
2,2,118,118,innerTrain,001_9T_(MM_003.10)_WB_at_Sip_Ave__Westbound__TRAFFICLAND_6434_2024-02-17-14:01:15.jpg,/home/csutter/cron/data/TRAFFICLAND_6434/20240217/001_9T_(MM_003.10)_WB_at_Sip_Ave__Westbound__TRAFFICLAND_6434_2024-02-17-14:01:15.jpg,TRAFFICLAND_6434,dry,0,day,"{Timestamp('2024-02-17 11:19:56.575438'): 'dawn', Timestamp('2024-02-17 11:48:27.257341'): 'sunrise', Timestamp('2024-02-17 22:32:47.637129'): 'sunset', Timestamp('2024-02-17 23:01:19.793499'): 'dusk'}",0.042088,0.076546,0.613636,0.133247,0.134484,0.613636,/home/csutter/cron/data/TRAFFICLAND_6434/20240217/001_9T_(MM_003.10)_WB_at_Sip_Ave__Westbound__TRAFFICLAND_6434_2024-02-17-14:01:15.jpg,innerTrain,0,40.734547,-74.081143,2024,2,17,20240217,14:01:15,20240217,14:01:15 20240217,2024-02-17 14:01:15,2024-02-17 14:00:00,2024-02-17 12:00:00,12,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t12z_02.parquet,"[40.73058990877996, -74.09561734113817]",1.299276,2024-02-17 12:00:00,2024-02-17 14:00:00,40.73059,-74.095617,272.47552,271.97363,0.00341,271.74094,95.3,-0.226598,-1.400036,1.553209,0.004438,0.433,7.85714,0.0,100792.0,241.0,280.1,100.0,5286.1255,220.63715,0.0,500.0,1.418255,0.048368,0.087969,0.555981,0.153131,0.154552,snow,0.555981,False,0,0.613636,snow,0.170797,0.060457,0.515464,0.085236,0.168047,0.515464,snow,0.321429,0.05764,0.162454,0.161124,0.297354,0.321429,wet,0.393162,0.013316,0.207839,0.134361,0.251322,0.393162,wet,0.242422,0.04558,0.333333,0.127001,0.251664,0.333333,snow,"['snow', 'snow', 'wet', 'wet', 'snow']","[0.6136363636363636, 0.5154639175257734, 0.3214285714285714, 0.3931623931623931, 0.3333333333333333]","{'snow': ['m0', 'm1', 'm4'], 'wet': ['m2', 'm3']}","{'snow': 3, 'wet': 2}","{'snow': 0.48747787149849003, 'wet': 0.35729548229548225}",{'snow': 0.6136363636363636},0.043816,0.366545,0.128194,0.252459,0.208987,snow,0.366545,snow,snow,True,True,True,snow,align_avg_mode,False,False,3,1,1,1.0,medium,0.366545

,Unnamed: 0,Unnamed: 0.2,Unnamed: 0.1,innerPhase_x,img_name,img_orig,site,img_cat,foldnum_x,timeofday,timeofevent,m0_calib_prob_dry,m0_calib_prob_poor_viz,m0_calib_prob_snow,m0_calib_prob_snow_severe,m0_calib_prob_wet,m0_calib_prob,img_orig_hrrr,innerPhase_y,foldnum_y,Latitude,Longitude,yr,mo,day,date,time,ymd,date_and_time_str,date_and_time_dt,date_and_time_dt_round,date_and_time_dt_init,init_hr,init_year,init_month,init_day,init_yyyymmdd,hrrr_file,HRRR_latlon,HRRR_distkm,time.1,valid_time,latitude,longitude,t2m,pt,sh2,d2m,r2,u10,v10,si10,asnow,tp,orog,cape,mslma,dswrf,dlwrf,tcc,gh,dpt,atmosphere,isobaricInhPa,uavg,o_prob_dry,o_prob_poor_viz,o_prob_snow,o_prob_snow_severe,o_prob_wet,o_pred,o_prob,classifier_TF,classifier_01,o_prob_calib,m0_calib_pred,m1_calib_prob_wet,m1_calib_prob_dry,m1_calib_prob_snow,m1_calib_prob_snow_severe,m1_calib_prob_poor_viz,m1_calib_prob,m1_calib_pred,m2_calib_prob_wet,m2_calib_prob_dry,m2_calib_prob_snow,m2_calib_prob_snow_severe,m2_calib_prob_poor_viz,m2_calib_prob,m2_calib_pred,m3_calib_prob_wet,m3_calib_prob_dry,m3_calib_prob_snow,m3_calib_prob_snow_severe,m3_calib_prob_poor_viz,m3_calib_prob,m3_calib_pred,m4_calib_prob_wet,m4_calib_prob_dry,m4_calib_prob_snow,m4_calib_prob_snow_severe,m4_calib_prob_poor_viz,m4_calib_prob,m4_calib_pred,list_5preds,list_5probs,dict_catAsKeys_modelAsValues,dict_catAsKeys_countAsValues,dict_catAsKeys_probsAsValues,dict_mostConfident_singleModel,ensembleAvg_dry,ensembleAvg_snow,ensembleAvg_snow_severe,ensembleAvg_wet,ensembleAvg_poor_viz,ensembleAvg_pred,ensembleAvg_predprob,ensembleMode_pred,ensembleMaxConf_pred,methodalign_1_2,methodalign_1_3,methodalign_2_3,select,decision,select_correct,ok_select,num_models_pred_cat,conf_consist,conf_probability,conf_overall,confidence,select_prob
0,0,2105,2105,innerTrain,001_9T_(MM_002.00)_WB_E_of_Hackey_Brdg__Westbound__TRAFFICLAND_6427_2024-02-17-14:01:14.jpg,/home/csutter/cron/data/TRAFFICLAND_6427/20240217/001_9T_(MM_002.00)_WB_E_of_Hackey_Brdg__Westbound__TRAFFICLAND_6427_2024-02-17-14:01:14.jpg,TRAFFICLAND_6427,dry,0,day,"{Timestamp('2024-02-17 11:19:59.724745'): 'dawn', Timestamp('2024-02-17 11:48:30.340348'): 'sunrise', Timestamp('2024-02-17 22:32:51.153503'): 'sunset', Timestamp('2024-02-17 23:01:23.243334'): 'dusk'}",0.042088,0.076546,0.613636,0.133247,0.134484,0.613636,/home/csutter/cron/data/TRAFFICLAND_6427/20240217/001_9T_(MM_002.00)_WB_E_of_Hackey_Brdg__Westbound__TRAFFICLAND_6427_2024-02-17-14:01:14.jpg,innerTrain,0,40.732063,-74.094898,2024,2,17,20240217,14:01:14,20240217,14:01:14 20240217,2024-02-17 14:01:14,2024-02-17 14:00:00,2024-02-17 12:00:00,12,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t12z_02.parquet,"[40.73058990877996, -74.09561734113817]",0.174507,2024-02-17 12:00:00,2024-02-17 14:00:00,40.73059,-74.095617,272.47552,271.97363,0.00341,271.74094,95.3,-0.226598,-1.400036,1.553209,0.004438,0.433,7.85714,0.0,100792.0,241.0,280.1,100.0,5286.1255,220.63715,0.0,500.0,1.418255,0.048368,0.087969,0.555981,0.153131,0.154552,snow,0.555981,False,0,0.613636,snow,0.170797,0.060457,0.515464,0.085236,0.168047,0.515464,snow,0.321429,0.05764,0.162454,0.161124,0.297354,0.321429,wet,0.393162,0.013316,0.207839,0.134361,0.251322,0.393162,wet,0.242422,0.04558,0.333333,0.127001,0.251664,0.333333,snow,"['snow', 'snow', 'wet', 'wet', 'snow']","[0.6136363636363636, 0.5154639175257734, 0.3214285714285714, 0.3931623931623931, 0.3333333333333333]","{'snow': ['m0', 'm1', 'm4'], 'wet': ['m2', 'm3']}","{'snow': 3, 'wet': 2}","{'snow': 0.48747787149849003, 'wet': 0.35729548229548225}",{'snow': 0.6136363636363636},0.043816,0.366545,0.128194,0.252459,0.208987,snow,0.366545,snow,snow,True,True,True,snow,align_avg_mode,False,False,3,1,1,1.0,low,0.366545
1,1,1050,1050,innerTrain,001_9T_(MM_002.74)_EB_at_Duncan_Ave__Eastbound__TRAFFICLAND_6437_2024-02-17-14:01:15.jpg,/home/csutter/cron/data/TRAFFICLAND_6437/20240217/001_9T_(MM_002.74)_EB_at_Duncan_Ave__Eastbound__TRAFFICLAND_6437_2024-02-17-14:01:15.jpg,TRAFFICLAND_6437,dry,0,day,"{Timestamp('2024-02-17 11:19:57.298875'): 'dawn', Timestamp('2024-02-17 11:48:27.874740'): 'sunrise', Timestamp('2024-02-17 22:32:48.941078'): 'sunset', Timestamp('2024-02-17 23:01:20.991025'): 'dusk'}",0.042088,0.076546,0.613636,0.133247,0.134484,0.613636,/home/csutter/cron/data/TRAFFICLAND_6437/20240217/001_9T_(MM_002.74)_EB_at_Duncan_Ave__Eastbound__TRAFFICLAND_6437_2024-02-17-14:01:15.jpg,innerTrain,0,40.730568,-74.085155,2024,2,17,20240217,14:01:15,20240217,14:01:15 20240217,2024-02-17 14:01:15,2024-02-17 14:00:00,2024-02-17 12:00:00,12,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t12z_02.parquet,"[40.73058990877996, -74.09561734113817]",0.883829,2024-02-17 12:00:00,2024-02-17 14:00:00,40.73059,-74.095617,272.47552,271.97363,0.00341,271.74094,95.3,-0.226598,-1.400036,1.553209,0.004438,0.433,7.85714,0.0,100792.0,241.0,280.1,100.0,5286.1255,220.63715,0.0,500.0,1.418255,0.048368,0.087969,0.555981,0.153131,0.154552,snow,0.555981,False,0,0.613636,snow,0.170797,0.060457,0.515464,0.085236,0.168047,0.515464,snow,0.321429,0.05764,0.162454,0.161124,0.297354,0.321429,wet,0.393162,0.013316,0.207839,0.134361,0.251322,0.393162,wet,0.242422,0.04558,0.333333,0.127001,0.251664,0.333333,snow,"['snow', 'snow', 'wet', 'wet', 'snow']","[0.6136363636363636, 0.5154639175257734, 0.3214285714285714, 0.3931623931623931, 0.3333333333333333]","{'snow': ['m0', 'm1', 'm4'], 'wet': ['m2', 'm3']}","{'snow': 3, 'wet': 2}","{'snow': 0.48747787149849003, 'wet': 0.35729548229548225}",{'snow': 0.6136363636363636},0.043816,0.366545,0.128194,0.252459,0.208987,snow,0.366545,snow,snow,True,True,True,snow,align_avg_mode,False,False,3,1,1,1.0,low,0.366545
2,2,118,118,innerTrain,001_9T_(MM_003.10)_WB_at_Sip_Ave__Westbound__TRAFFICLAND_6434_2024-02-17-14:01:15.jpg,/home/csutter/cron/data/TRAFFICLAND_6434/20240217/001_9T_(MM_003.10)_WB_at_Sip_Ave__Westbound__TRAFFICLAND_6434_2024-02-17-14:01:15.jpg,TRAFFICLAND_6434,dry,0,day,"{Timestamp('2024-02-17 11:19:56.575438'): 'dawn', Timestamp('2024-02-17 11:48:27.257341'): 'sunrise', Timestamp('2024-02-17 22:32:47.637129'): 'sunset', Timestamp('2024-02-17 23:01:19.793499'): 'dusk'}",0.042088,0.076546,0.613636,0.133247,0.134484,0.613636,/home/csutter/cron/data/TRAFFICLAND_6434/20240217/001_9T_(MM_003.10)_WB_at_Sip_Ave__Westbound__TRAFFICLAND_6434_2024-02-17-14:01:15.jpg,innerTrain,0,40.734547,-74.081143,2024,2,17,20240217,14:01:15,20240217,14:01:15 20240217,2024-02-17 14:01:15,2024-02-17 14:00:00,2024-02-17 12:00:00,12,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t12z_02.parquet,"[40.73058990877996, -74.09561734113817]",1.299276,2024-02-17 12:00:00,2024-02-17 14:00:00,40.73059,-74.095617,272.47552,271.97363,0.00341,271.74094,95.3,-0.226598,-1.400036,1.553209,0.004438,0.433,7.85714,0.0,100792.0,241.0,280.1,100.0,5286.1255,220.63715,0.0,500.0,1.418255,0.048368,0.087969,0.555981,0.153131,0.154552,snow,0.555981,False,0,0.613636,snow,0.170797,0.060457,0.515464,0.085236,0.168047,0.515464,snow,0.321429,0.05764,0.162454,0.161124,0.297354,0.321429,wet,0.393162,0.013316,0.207839,0.134361,0.251322,0.393162,wet,0.242422,0.04558,0.333333,0.127001,0.251664,0.333333,snow,"['snow', 'snow', 'wet', 'wet', 'snow']","[0.6136363636363636, 0.5154639175257734, 0.3214285714285714, 0.3931623931623931, 0.3333333333333333]","{'snow': ['m0', 'm1', 'm4'], 'wet': ['m2', 'm3']}","{'snow': 3, 'wet': 2}","{'snow': 0.48747787149849003, 'wet': 0.35729548229548225}",{'snow': 0.6136363636363636},0.043816,0.366545,0.128194,0.252459,0.208987,snow,0.366545,snow,snow,True,True,True,snow,align_avg_mode,False,False,3,1,1,1.0,low,0.366545

In [21]:
d.head(4)

,Unnamed: 0,Unnamed: 0.2,Unnamed: 0.1,innerPhase_x,img_name,img_orig,site,img_cat,foldnum_x,timeofday,timeofevent,m0_calib_prob_dry,m0_calib_prob_poor_viz,m0_calib_prob_snow,m0_calib_prob_snow_severe,m0_calib_prob_wet,m0_calib_prob,img_orig_hrrr,innerPhase_y,foldnum_y,Latitude,Longitude,yr,mo,day,date,time,ymd,date_and_time_str,date_and_time_dt,date_and_time_dt_round,date_and_time_dt_init,init_hr,init_year,init_month,init_day,init_yyyymmdd,hrrr_file,HRRR_latlon,HRRR_distkm,time.1,valid_time,latitude,longitude,t2m,pt,sh2,d2m,r2,u10,v10,si10,asnow,tp,orog,cape,mslma,dswrf,dlwrf,tcc,gh,dpt,atmosphere,isobaricInhPa,uavg,o_prob_dry,o_prob_poor_viz,o_prob_snow,o_prob_snow_severe,o_prob_wet,o_pred,o_prob,classifier_TF,classifier_01,o_prob_calib,m0_calib_pred,m1_calib_prob_wet,m1_calib_prob_dry,m1_calib_prob_snow,m1_calib_prob_snow_severe,m1_calib_prob_poor_viz,m1_calib_prob,m1_calib_pred,m2_calib_prob_wet,m2_calib_prob_dry,m2_calib_prob_snow,m2_calib_prob_snow_severe,m2_calib_prob_poor_viz,m2_calib_prob,m2_calib_pred,m3_calib_prob_wet,m3_calib_prob_dry,m3_calib_prob_snow,m3_calib_prob_snow_severe,m3_calib_prob_poor_viz,m3_calib_prob,m3_calib_pred,m4_calib_prob_wet,m4_calib_prob_dry,m4_calib_prob_snow,m4_calib_prob_snow_severe,m4_calib_prob_poor_viz,m4_calib_prob,m4_calib_pred,list_5preds,list_5probs,dict_catAsKeys_modelAsValues,dict_catAsKeys_countAsValues,dict_catAsKeys_probsAsValues,dict_mostConfident_singleModel,ensembleAvg_dry,ensembleAvg_snow,ensembleAvg_snow_severe,ensembleAvg_wet,ensembleAvg_poor_viz,ensembleAvg_pred,ensembleAvg_predprob,ensembleMode_pred,ensembleMaxConf_pred,methodalign_1_2,methodalign_1_3,methodalign_2_3,select,decision,select_correct,ok_select,num_models_pred_cat,conf_consist,conf_probability,conf_overall,confidence,select_prob
0,0,2105,2105,innerTrain,001_9T_(MM_002.00)_WB_E_of_Hackey_Brdg__Westbound__TRAFFICLAND_6427_2024-02-17-02:01:21.jpg,/home/csutter/cron/data/TRAFFICLAND_6427/20240217/001_9T_(MM_002.00)_WB_E_of_Hackey_Brdg__Westbound__TRAFFICLAND_6427_2024-02-17-02:01:21.jpg,TRAFFICLAND_6427,dry,0,night,"{Timestamp('2024-02-17 11:19:59.724745'): 'dawn', Timestamp('2024-02-17 11:48:30.340348'): 'sunrise', Timestamp('2024-02-17 22:32:51.153503'): 'sunset', Timestamp('2024-02-17 23:01:23.243334'): 'dusk'}",0.850543,0.023381,0.041313,0.021458,0.063304,0.850543,/home/csutter/cron/data/TRAFFICLAND_6427/20240217/001_9T_(MM_002.00)_WB_E_of_Hackey_Brdg__Westbound__TRAFFICLAND_6427_2024-02-17-02:01:21.jpg,innerTrain,0,40.732063,-74.094898,2024,2,17,20240217,02:01:21,20240217,02:01:21 20240217,2024-02-17 02:01:21,2024-02-17 02:00:00,2024-02-17,0,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t00z_02.parquet,"[40.73058990877996, -74.09561734113817]",0.174507,2024-02-17,2024-02-17 02:00:00,40.730590,-74.095617,273.56964,272.68512,0.00220,265.9998,52.7,-0.995306,-1.59118,2.667564,0.0,0.0,7.85714,0.0,101286.0,0.0,230.1,100.0,5399.7676,246.31229,0.0,500.0,1.876829,0.826100,0.027205,0.048070,0.024968,0.073657,dry,0.826100,True,1,0.850543,dry,0.051247,0.892754,0.003865,0.008316,0.043819,0.892754,dry,0.199680,0.555556,0.045369,0.018759,0.180637,0.555556,dry,0.129602,0.521212,0.020416,0.032303,0.296467,0.521212,dry,0.147035,0.524229,0.064798,0.078445,0.185493,0.524229,dry,"['dry', 'dry', 'dry', 'dry', 'dry']","[0.8505434782608695, 0.8927536231884058, 0.5555555555555555, 0.5212121212121212, 0.5242290748898678]","{'dry': ['m0', 'm1', 'm2', 'm3', 'm4']}",{'dry': 5},{'dry': 0.6688587706213639},{'dry': 0.8927536231884058},0.668859,0.035152,0.031856,0.118174,0.145959,dry,0.668859,dry,dry,True,True,True,dry,align_avg_mode,True,True,5,3,2,2.5,high,0.668859
1,1,1050,1050,innerTrain,001_9T_(MM_002.74)_EB_at_Duncan_Ave__Eastbound__TRAFFICLAND_6437_2024-02-17-02:01:22.jpg,/home/csutter/cron/data/TRAFFICLAND_6437/20240217/001_9T_(MM_002.74)_EB_at_Duncan_Ave__Eastbound__TRAFFICLAND_6437_2024-02-17-02:01:22.jpg,TRAFFICLAND_6437,dry,0,night,"{Timestamp('2024-02-17 11:19:57.298875'): 'dawn', Timestamp('2024-02-17 11:48:27.874740'): 'sunrise', Timestamp('2024-02-17 22:32:48.941078'): 'sunset', Timestamp('2024-02-17 23:01:20.991025'): 'dusk'}",0.850543,0.023381,0.041313,0.021458,0.063304,0.850543,/home/csutter/cron/data/TRAFFICLAND_6437/20240217/001_9T_(MM_002.74)_EB_at_Duncan_Ave__Eastbound__TRAFFICLAND_6437_2024-02-17-02:01:22.jpg,innerTrain,0,40.730568,-74.085155,2024,2,17,20240217,02:01:22,20240217,02:01:22 20240217,2024-02-17 02:01:22,2024-02-17 02:00:00,2024-02-17,0,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t00z_02.parquet,"[40.73058990877996, -74.09561734113817]",0.883829,2024-02-17,2024-02-17 02:00:00,40.730590,-74.095617,273.56964,272.68512,0.00220,265.9998,52.7,-0.995306,-1.59118,2.667564,0.0,0.0,7.85714,0.0,101286.0,0.0,230.1,100.0,5399.7676,246.31229,0.0,500.0,1.876829,0.826100,0.027205,0.048070,0.024968,0.073657,dry,0.826100,True,1,0.850543,dry,0.051247,0.892754,0.003865,0.008316,0.043819,0.892754,dry,0.199680,0.555556,0.045369,0.018759,0.180637,0.555556,dry,0.129602,0.521212,0.020416,0.032303,0.296467,0.521212,dry,0.147035,0.524229,0.064798,0.078445,0.185493,0.524229,dry,"['dry', 'dry', 'dry', 'dry', 'dry']","[0.8505434782608695, 0.8927536231884058, 0.5555555555555555, 0.5212121212121212, 0.5242290748898678]","{'dry': ['m0', 'm1', 'm2', 'm3', 'm4']}",{'dry': 5},{'dry': 0.6688587706213639},{'dry': 0.8927536231884058},0.668859,0.035152,0.031856,0.118174,0.145959,dry,0.668859,dry,dry,True,True,True,dry,align_avg_mode,True,True,5,3,2,2.5,high,0.668859
2,2,118,118,innerTrain,001_9T_(MM_003.10)_WB_at_Sip_Ave__Westbound__TRAFFICLAND_6434_2024-02-17-02:01:22.jpg,/home/csutter/cron/data/TRAFFICLAND_6434/20240217/001_9T_(MM_003.10)_WB_at_Sip_Ave__Westbound__TRAFFICLAND_6434_2024-02-17-02:01:22.jpg,TRAFFICLAND_6434,dry,0,night,"{Timestamp('2024-02-17 11:19:56.575438'): 'dawn', Timestamp('2024-02-17 11:48:27.257341'): 'sunrise', Timestamp('2024-02-17 22:32:47.637129'): 'sunset', Timestamp('2024-02-17 23:01:19.793499'): 'dusk'}",0.850543,0.023381,0.041313,0.021458,0.063304,0.850543,/home/csutter/cron/data/TRAFFICLAND_6434/20240217/001_9T_(MM_003.10)_WB_at_Sip_Ave__Westbound__TRAFFICLAND_6434_2024-02-17-02:01:22.jpg,innerTrain,0,40.734547,-74.081143,2024,2,17,20240217,02:01:22,20240217,02:01:22 20240217,2024-02-17 02:01:22,2024-02-17 02:00:00,2024-02-17,0,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t00z_02.parquet,"[40.73058990877996, -74.09561734113817]",1.299276,2024-02-17,2024-02-17 02:00:00,40.730590,-74.095617,273.56964,272.68512,0.00220,265.9998,52.7,-0.995306,-1.59118,2.667564,0.0,0.0,7.85714,0.0,101286.0,0.0,230.1,100.0,5399.7676,246.31229,0.0,500.0,1.876829,0.826100,0.027205,0.048070,0.024968,0.073657,dry,0.826100,True,1,0.850543,dry,0.051247,0.892754,0.003865,0.008316,0.043819,0.892754,dry,0.199680,0.555556,0.045369,0.018759,0.180637,0.555556,dry,0.129602,0.521212,0.020416,0.032303,0.296467,0.521212,dry,0.147035,0.524229,0.064798,0.078445,0.185493,0.524229,dry,"['dry', 'dry', 'dry', 'dry', 'dry']","[0.8505434782608695, 0.8927536231884058, 0.5555555555555555, 0.5212121212121212, 0.5242290748898678]","{'dry': ['m0', 'm1', 'm2', 'm3', 'm4']}",{'dry': 5},{'dry': 0.6688587706213639},{'dry': 0.8927536231884058},0.668859,0.035152,0.031856,0.118174,0.145959,dry,0.668859,dry,dry,True,True,True,dry,align_avg_mode,True,True,5,3,2,2.5,high,0.668859
3,3,1942,1942,innerTrain,001_9_(MM_000.56)_WB_at_Doremus_Ave__Westbound__TRAFFICLAND_6428_2024-02-17-02:01:21.jpg,/home/csutter/cron/data/TRAFFICLAND_6428/20240217/001_9_(MM_000.56)_WB_at_Doremus_Ave__Westbound__TRAFFICLAND_6428_2024-02-17-02:01:21.jpg,TRAFFICLAND_6428,dry,0,night,"{Timestamp('2024-02-17 11:20:06.634321'): 'dawn', Timestamp('2024-02-17 11:48:37.308014'): 'sunrise', Timestamp('2024-02-17 22:32:57.756188'): 'sunset', Timestamp('2024-02-17 23:01:29.904327'): 'dusk'}",0.850543,0.024001,0.039572,0.020044,0.065839,0.850543,/home/csutter/cron/data/TRAFFICLAND_6428/20240217/001_9_(MM_000.56)_WB_at_Doremus_Ave__Westbound__TRAFFICLAND_6428_2024-02-17-02:01:21.jpg,innerTrain,0,40.734253,-74.123166,2024,2,17,20240217,02:01:21,20240217,02:01:21 20240217,2024-02-17 02:01:21,2024-02-17 02:00:00,2024-02-17,0,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t00z_02.parquet,"[40.73736644727456, -74.13005141845099]",0.676619,2024-02-17,2024-02-17 02:00:00,40.737366,-74.130051,273.63214,272.68512,0.00246,267.4373,60.2,-1.057806,-1.40368,2.667564,0.0,0.0,3.35714,0.0,101284.0,0.0,228.1,100.0,5399.4240,246.24979,0.0,500.0,1.757632,0.819033,0.029061,0.047915,0.024270,0.079721,dry,0.819033,True,1,0.850543,dry,0.050959,0.892754,0.003885,0.008358,0.044044,0.892754,dry,0.224689,0.526882,0.040342,0.014993,0.193095,0.526882,dry,0.147099,0.454006,0.023249,0.031987,0.343659,0.454006,dry,0.150855,0.524229,0.061041,0.080013,0.183862,0.524229,dry,"['dry', 'dry', 'dry', 'dry', 'dry']","[0.8505434782608695, 0.8927536231884058, 0.5268817204301075, 0.4540059347181009, 0.5242290748898678]","{'dry': ['m0', 'm1', 'm2', 'm3', 'm4']}",{'dry': 5},{'dry': 0.6496827662974702},{'dry': 0.8927536231884058},0.649683,0.033618,0.031079,0.127888,0.157732,dry,0.649683,dry,dry,True,True,True,dry,align_avg_mode,True,True,5,3,2,2.5,high,0.649683

In [18]:
np.unique(d["decision"])

array(['align_avg_maxConf', 'align_avg_mode', 'align_mode_maxConf',
       'tie_use_most_severe'], dtype=object)

In [20]:
d[d['decision']=='align_mode_maxConf']

,Unnamed: 0,Unnamed: 0.2,Unnamed: 0.1,innerPhase_x,img_name,img_orig,site,img_cat,foldnum_x,timeofday,timeofevent,m0_calib_prob_dry,m0_calib_prob_poor_viz,m0_calib_prob_snow,m0_calib_prob_snow_severe,m0_calib_prob_wet,m0_calib_prob,img_orig_hrrr,innerPhase_y,foldnum_y,Latitude,Longitude,yr,mo,day,date,time,ymd,date_and_time_str,date_and_time_dt,date_and_time_dt_round,date_and_time_dt_init,init_hr,init_year,init_month,init_day,init_yyyymmdd,hrrr_file,HRRR_latlon,HRRR_distkm,time.1,valid_time,latitude,longitude,t2m,pt,sh2,d2m,r2,u10,v10,si10,asnow,tp,orog,cape,mslma,dswrf,dlwrf,tcc,gh,dpt,atmosphere,isobaricInhPa,uavg,o_prob_dry,o_prob_poor_viz,o_prob_snow,o_prob_snow_severe,o_prob_wet,o_pred,o_prob,classifier_TF,classifier_01,o_prob_calib,m0_calib_pred,m1_calib_prob_wet,m1_calib_prob_dry,m1_calib_prob_snow,m1_calib_prob_snow_severe,m1_calib_prob_poor_viz,m1_calib_prob,m1_calib_pred,m2_calib_prob_wet,m2_calib_prob_dry,m2_calib_prob_snow,m2_calib_prob_snow_severe,m2_calib_prob_poor_viz,m2_calib_prob,m2_calib_pred,m3_calib_prob_wet,m3_calib_prob_dry,m3_calib_prob_snow,m3_calib_prob_snow_severe,m3_calib_prob_poor_viz,m3_calib_prob,m3_calib_pred,m4_calib_prob_wet,m4_calib_prob_dry,m4_calib_prob_snow,m4_calib_prob_snow_severe,m4_calib_prob_poor_viz,m4_calib_prob,m4_calib_pred,list_5preds,list_5probs,dict_catAsKeys_modelAsValues,dict_catAsKeys_countAsValues,dict_catAsKeys_probsAsValues,dict_mostConfident_singleModel,ensembleAvg_dry,ensembleAvg_snow,ensembleAvg_snow_severe,ensembleAvg_wet,ensembleAvg_poor_viz,ensembleAvg_pred,ensembleAvg_predprob,ensembleMode_pred,ensembleMaxConf_pred,methodalign_1_2,methodalign_1_3,methodalign_2_3,select,decision,select_correct,ok_select,num_models_pred_cat,conf_consist,conf_probability,conf_overall,confidence,select_prob
810,810,393,393,innerTrain,I_81_north_of_Exit_14_(Inspection)__Southbound__Skyline_8356_2024-02-17-02:01:08.jpg,/home/csutter/cron/data/Skyline_8356/20240217/I_81_north_of_Exit_14_(Inspection)__Southbound__Skyline_8356_2024-02-17-02:01:08.jpg,Skyline_8356,dry,0,night,"{Timestamp('2024-02-17 11:30:15.376150'): 'dawn', Timestamp('2024-02-17 11:59:45.903134'): 'sunrise', Timestamp('2024-02-17 22:37:49.424331'): 'sunset', Timestamp('2024-02-17 23:07:21.642498'): 'dusk'}",0.613636,0.122620,0.064536,0.148418,0.050791,0.613636,/home/csutter/cron/data/Skyline_8356/20240217/I_81_north_of_Exit_14_(Inspection)__Southbound__Skyline_8356_2024-02-17-02:01:08.jpg,innerTrain,0,42.857899,-76.118887,2024,2,17,20240217,02:01:08,20240217,02:01:08 20240217,2024-02-17 02:01:08,2024-02-17 02:00:00,2024-02-17,0,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t00z_02.parquet,"[42.85117513986955, -76.10663121173684]",1.249539,2024-02-17,2024-02-17 02:00:00,42.851175,-76.106631,266.69464,270.06012,0.00204,264.3123,73.5,0.879694,1.59632,2.542564,0.000000,0.000,450.51340,0.0,101275.0,0.0,226.5,100.0,5308.6426,242.31229,0.0,500.0,1.822663,0.590987,0.129808,0.068319,0.157118,0.053768,dry,0.590987,True,1,0.613636,dry,0.084455,0.710769,0.023141,0.079941,0.101694,0.710769,dry,0.129971,0.214093,0.024649,0.120175,0.511111,0.511111,poor_viz,0.126830,0.363708,0.022411,0.082142,0.404908,0.404908,poor_viz,0.035634,0.080369,0.034034,0.088059,0.761905,0.761905,poor_viz,"['dry', 'dry', 'poor_viz', 'poor_viz', 'poor_viz']","[0.6136363636363636, 0.7107692307692308, 0.5111111111111111, 0.4049079754601227, 0.7619047619047619]","{'dry': ['m0', 'm1'], 'poor_viz': ['m2', 'm3', 'm4']}","{'dry': 2, 'poor_viz': 3}","{'dry': 0.6622027972027973, 'poor_viz': 0.5593079494919985}",{'poor_viz': 0.7619047619047619},0.396515,0.033754,0.103747,0.085536,0.380448,dry,0.396515,poor_viz,poor_viz,False,False,True,poor_viz,align_mode_maxConf,False,False,3,1,1,1.0,medium,0.380448
1054,1054,2128,2128,innerTrain,I_88_at_Worcester_Rest_Area__Eastbound__Skyline_6309_2024-02-17-02:01:04.jpg,/home/csutter/cron/data/Skyline_6309/20240217/I_88_at_Worcester_Rest_Area__Eastbound__Skyline_6309_2024-02-17-02:01:04.jpg,Skyline_6309,dry,0,night,"{Timestamp('2024-02-17 11:24:33.425963'): 'dawn', Timestamp('2024-02-17 11:53:55.532007'): 'sunrise', Timestamp('2024-02-17 22:32:50.640715'): 'sunset', Timestamp('2024-02-17 23:02:14.407303'): 'dusk'}",0.449541,0.026740,0.210026,0.094340,0.219352,0.449541,/home/csutter/cron/data/Skyline_6309/20240217/I_88_at_Worcester_Rest_Area__Eastbound__Skyline_6309_2024-02-17-02:01:04.jpg,innerTrain,0,42.572847,-74.767091,2024,2,17,20240217,02:01:04,20240217,02:01:04 20240217,2024-02-17 02:01:04,2024-02-17 02:00:00,2024-02-17,0,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t00z_02.parquet,"[42.58228112547757, -74.76360913203473]",1.086271,2024-02-17,2024-02-17 02:00:00,42.582281,-74.763609,266.31964,270.12262,0.00220,265.1873,85.9,1.317194,1.15882,2.355064,0.000036,0.002,490.91965,0.0,101246.0,0.0,262.0,79.0,5319.4550,242.49979,0.0,500.0,1.754384,0.366334,0.030782,0.241774,0.108601,0.252510,dry,0.366334,True,1,0.449541,dry,0.224458,0.426277,0.177679,0.073044,0.098542,0.426277,dry,0.239748,0.273883,0.100166,0.064008,0.322195,0.322195,poor_viz,0.199412,0.199770,0.106188,0.042191,0.452440,0.452440,poor_viz,0.277469,0.000000,0.233837,0.220221,0.268472,0.277469,wet,"['dry', 'dry', 'poor_viz', 'poor_viz', 'wet']","[0.4495412844036697, 0.4262772913802233, 0.3221946798196772, 0.4524395985522391, 0.2774694613150401]","{'dry': ['m0', 'm1'], 'poor_viz': ['m2', 'm3'], 'wet': ['m4']}","{'dry': 2, 'poor_viz': 2, 'wet': 1}","{'dry': 0.4379092878919465, 'poor_viz': 0.3873171391859581, 'wet': 0.2774694613150401}",{'poor_viz': 0.4524395985522391},0.269894,0.165579,0.098761,0.232088,0.233678,dry,0.269894,poor_viz,poor_viz,False,False,True,poor_viz,align_mode_maxConf,False,False,2,1,1,1.0,medium,0.233678
1876,1876,1253,1253,innerTrain,NY_33_at_Fillmore_Avenue__Westbound__Skyline_5627_2024-02-17-02:01:11.jpg,/home/csutter/cron/data/Skyline_5627/20240217/NY_33_at_Fillmore_Avenue__Westbound__Skyline_5627_2024-02-17-02:01:11.jpg,Skyline_5627,dry,0,night,"{Timestamp('2024-02-17 11:41:12.013624'): 'dawn', Timestamp('2024-02-17 12:10:44.555944'): 'sunrise', Timestamp('2024-02-17 22:48:36.731183'): 'sunset', Timestamp('2024-02-17 23:18:10.972580'): 'dusk'}",0.000000,0.035690,0.410790,0.183688,0.369832,0.410790,/home/csutter/cron/data/Skyline_5627/20240217/NY_33_at_Fillmore_Avenue__Westbound__Skyline_5627_2024-02-17-02:01:11.jpg,innerTrain,0,42.926272,-78.839607,2024,2,17,20240217,02:01:11,20240217,02:01:11 20240217,2024-02-17 02:01:11,2024-02-17 02:00:00,2024-02-17,0,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t00z_02.parquet,"[42.93378214865497, -78.82667125932352]",1.345805,2024-02-17,2024-02-17 02:00:00,42.933782,-78.826671,269.81964,270.74762,0.00236,266.5623,77.1,2.567194,0.15882,2.542564,0.000122,0.010,204.41965,0.0,101415.0,0.0,272.1,100.0,5297.0800,241.31229,0.0,500.0,2.572102,0.301836,0.024918,0.286799,0.128244,0.258203,dry,0.301836,True,1,0.000000,snow,0.243631,0.471429,0.119830,0.095594,0.069517,0.471429,dry,0.292858,0.321429,0.108978,0.055217,0.221519,0.321429,dry,0.224613,0.266746,0.101962,0.031679,0.375000,0.375000,poor_viz,0.273729,0.286718,0.000000,0.175284,0.264268,0.286718,dry,"['snow', 'dry', 'dry', 'poor_viz', 'dry']","[0.4107902578318076, 0.4714285714285714, 0.3214285714285714, 0.375, 0.2867179357623856]","{'snow': ['m0'], 'dry': ['m1', 'm2', 'm4'], 'poor_viz': ['m3']}","{'snow': 1, 'dry': 3, 'poor_viz': 1}","{'snow': 0.4107902578318076, 'dry': 0.3598583595398428, 'poor_viz': 0.375}",{'dry': 0.4714285714285714},0.269264,0.148312,0.108292,0.280933,0.193199,wet,0.280933,dry,dry,False,False,True,dry,align_mode_maxConf,True,True,3,1,1,1.0,medium,0.269264
1883,1883,1555,1555,innerTrain,NY_33_at_Suffolk_Street__Westbound__Skyline_1821_2024-02-17-02:01:08.jpg,/home/csutter/cron/data/Skyline_1821/20240217/NY_33_at_Suffolk_Street__Westbound__Skyline_1821_2024-02-17-02:01:08.jpg,Skyline_1821,dry,0,night,"{Timestamp('2024-02-17 11:41:05.619801'): 'dawn', Timestamp('2024-02-17 12:10:38.374324'): 'sunrise', Timestamp('2024-02-17 22:48:29.231020'): 'sunset', Timestamp('2024-02-17 23:18:03.685376'): 'dusk'}",0.000000,0.035690,0.410790,0.183688,0.369832,0.410790,/home/csutter/cron/data/Skyline_1821/20240217/NY_33_at_Suffolk_Street__Westbound__Skyline_1821_2024-02-17-02:01:08.jpg,innerTrain,0,42.933353,-78.811085,2024,2,17,20240217,02:01:08,20240217,02:01:08 20240217,2024-02-17 02:01:08,2024-02-17 02:00:00,2024-02-17,0,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t00z_02.parquet,"[42.93378214865497, -78.82667125932352]",1.273180,2024-02-17,2024-02-17 02:00:00,42.933782,-78.826671,269.81964,270.74762,0.00236,266.5623,77.1,2.567194,0.15882,2.542564,0.000122,0.010,204.41965,0.0,101415.0,0.0,272.1,100.0,5297.0800,241.31229,0.0,500.0,2.572102,0.301836,0.024918,0.286799,0.128244,0.258203,dry,0.301836,True,1,0.000000,snow,0.243631,0.471429,0.119830,0.095594,0.069517,0.471429,dry,0.292858,0.321429,0.108978,0.055217,0.221519,0.321429,dry,0.224613,0.266746,0.101962,0.031679,0.375000,0.375000,poor_viz,0.273729,0.286718,0.000000,0.175284,0.264268,0.286718,dry,"['snow', 'dry', 'dry', 'poor_viz', 'dry']","[0.4107902578318076, 0.4714285714285714, 0.3214285714285714, 0.375, 0.2867179357623856]","{'snow': ['m0'], 'dry': ['m1', 'm2', 'm4'], 'poor_viz': ['m3']}","{'snow': 1, 'dry': 3, 'poor_viz': 1}","{'snow': 0.4107902578318076, 'dry': 0.3598583595398428, 'poor_viz': 0.375}",{'dry': 0.4714285714285714},0.269264,0.148312,0.108292,0.280933,0.193199,wet,0.280933,dry,dry,False,False,True,dry,align_mode_maxConf,True,True,3,1,1,1.0,medium,0.269264
1886,1886,1808,1808,innerTrain,NY_33_between_Fillmore_Avenue_and_Grider_Street__Westbound__Skyline_1819_2024-02-17-02:01:08.jpg,/home/csutter/cron/data/Skyline_1819/20240217/NY_33_between_Fillmore_Avenue_and_Grider_Street__Westbound__Skyline_1819_2024-02-17-02:01:08.jpg,Skyline_1819,dry,0,night,"{Timestamp('2024-02-17 11:41:10.575055'): 'dawn', Timestamp('2024-02-17 12:10:43.221284'): 'sunrise', Timestamp('2024-02-17 22:48:34.753657'): 'sunset', Timestamp('2024-02-17 23:18:09.099335'): 'dusk'}",0.000000,0.035690,0.410790,0.183688,0.369832,0.410790,/home/csutter/cron/data/Skyline_1819/20240217/NY_33_between_Fillmore_Avenue_and_Grider_Street__Westbound__Skyline_1819_2024-02-17-02:01:08.jpg,innerTrain,0,42.929742,-78.832698,2024,2,17,20240217,02:01:08,20240217,02:01:08 20240217,2024-02-17 02:01:08,2024-02-17 02:00:00,2024-02-17,0,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t00z_02.parquet,"[42.93378214865497, -78.82667125932352]",0.665942,2024-02-17,2024-02-17 02:00:00,42.933782,-78.826671,269.81964,270.74762,0.00236,266.5623,77.1,2.567194,0.15882,2.542564,0.000122,0.010,204.41965,0.0,101415.0,0.0,272.1,100.0,5297.0800,241.31229,0.0,500.0,2.572102,0.301836,0.024918,0.286799,0.128244,0.258203,dry,0.301836,True,1,0.000000,snow,0.243631,0.471429,0.119830,0.095594,0.069517,0.471429,dry,0.292858,0.321429,0.108978,0.055217,0.221519,0.321429,dry,0.224613,0.266746,0.101962,0.031679,0.375000,0.375000,poor_viz,0.273729,0.286718,0.000000,0.175284,0.264268,0.286718,dry,"['snow', 'dry', 'dry', 'poor_viz', 'dry']","[0.4107902578318076, 0.4714285714285714, 0.3214285714285714, 0.375, 0.2867179357623856]","{'snow': ['m0'], 'dry': ['m1', 'm2', 'm4'], 'poor_viz': ['m3']}","{'snow': 1, 'dry': 3, 'poor_viz': 1}","{'snow': 0.4107902578318076, 'dry': 0.3598583595398428, 'poor_viz': 0.375}",{'dry': 0.4714285714285714},0.269264,0.148312,0.108292,0.280933,0.193199,wet,0.280933,dry,dry,False,False,True,dry,align_mode_maxConf,True,True,3,1,1,1.0,medium,0.269264
1887,1887,1071,1071,innerTrain,NY_33_between_Grider_Street_and_Olympic_Avenue__Eastbound__Skyline_1820_2024-02-17-02:01:08.jpg,/home/csutter/cron/data/Skyline_1820/20240217/NY_33_between_Grider_Street_and_Olympic_Avenue__Eastbound__Skyline_1820_2024-02-17-02:01:08.jpg,Skyline_1820,dry,0,night,"{Timestamp('2024-02-17 11:41:07.888084'): 'dawn', Timestamp('2024-02-17 12:10:40.533795'): 'sunrise', Timestamp('2024-02-17 22:48:32.064906'): 'sunset', Timestamp('2024-02-17 23:18:06.410062'): 'dusk'}",0.000000,0.035690,0.410790,0.183688,0.369832,0.410790,/home/csutter/cron/data/Skyline_1820/20240217/NY_33_between_Grider_Street_and_Olympic_Avenue__Eastbound__Skyline_1820_2024-02-17-02:01:08.jpg,innerTrain,0,42.929721,-78.821497,2024,2,17,20240217,02:01:08,20240217,02:01:08 20240217,2024-02-17 02:01:08,2024-02-17 02:00:00,2024-02-17,0,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t00z_02.parquet,"[42.93378214865497, -78.82667125932352]",0.618021,2024-02-17,2024-02-17 02:00:00,42.933782,-78.826671,269.81964,270.74762,0.00236,266.5623,77.1,2.567194,0.15882,2.542564,0.000122,0.010,204.41965,0.0,101415.0,0.0,272.1,100.0,5297.0800,241.31229,0.0,500.0,2.572102,0.301836,0.024918,0.286799,0.128244,0.258203,dry,0.301836,True,1,0.000000,snow,0.243631,0.471429,0.119830,0.095594,0.069517,0.471429,dry,0.292858,0.321429,0.108978,0.055217,0.221519,0.321429,dry,0.224613,0.266746,0.101962,0.031679,0.375000,0.375000,poor_viz,0.273729,0.286718,0.000000,0.175284,0.264268,0.286718,dry,"['snow', 'dry', 'dry', 'poor_viz', 'dry']","[0.4107902578318076, 0.4714285714285714, 0.3214285714285714, 0.375, 0.2867179357623856]","{'snow': ['m0'], 'dry': ['m1', 'm2', 'm4'], 'poor_viz': ['m3']}","{'snow': 1, 'dry': 3, 'poor_viz': 1}","{'snow': 0.4107902578318076, 'dry': 0.3598583595398428, 'poor_viz': 0.375}",{'dry': 0.4714285714285714},0.269264,0.148312,0.108292,0.280933,0.193199,wet,0.280933,dry,dry,False,False,True,dry,align_mode_maxConf,True,True,3,1,1,1.0,medium,0.269264
1935,1935,704,704,innerTrain,"NY_5A_at_NY_8,_12_South_Interchange___Utica_(2)__Westbound__Skyline_2104_2024-02-17-02:00:27.jpg","/home/csutter/cron/data/Skyline_2104/20240217/NY_5A_at_NY_8,_12_South_Interchange___Utica_(2)__Westbound__Skyline_2104_2024-02-17-02:00:27.jpg",Skyline_2104,dry,0,night,"{Timestamp('2024-02-17 11:27:00.187180'): 'dawn', Timestamp('2024-02-17 11:56:38.179734'): 'sunrise', Timestamp('2024-02-17 22:33:55.400679'): 'sunset', Timestamp('2024-02-17 23:03:35.111069'): 'dusk'}",0.166667,0.066215,0.373589,0.094045,0.299485,0.373589,"/home/csutter/cron/data/Skyline_2104/20240217/NY_5A_at_NY_8,_12_South_Interchange___Utica_(2)__Westbound__Skyline_2104_2024-02-17-02:00:27.jpg",innerTrain,0,43.106347,-75.239611,2024,2,17,20240217,02:00:27,20240217,02:00:27 20240217,2024-02-17 02:00:27,2024-02-17 02:00:00,2024-02-17,0,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t00z_02.parquet,"[43.11057314057041, -75.22665856772227]",1.154110,2024-02-17,2024-02-17 02:00:00,43.110573,-75.226659,269.25714,269.62262,0.00264,268.1248,89.3,0.879694,0.09632,2.167564,0.000040,0.003,129.91965,0.0,101229.0,0.0,278.1,100.0,5300.9863,240.81229,0.0,500.0,0.884951,0.342142,0.052272,0.294922,0.074242,0.236422,dry,0.342142,True,1,0.166667,snow,0.196211,0.423077,0.169356,0.053882,0.157475,0.423077,dry,0.285435,0.264123,0.080974,0.048039,0.321429,0.321429,poor_viz,0.257347,0.162281,0.091170,0.035196,0.454006,0.454006,poor_viz,0.342450,0.291654,0.208619,0.157277,0.000000,0.342450,wet,"['snow', 'dry', 'poor_viz', 'poor_viz', 'wet']","[0.3735892566479531, 0.4230769230769231, 0.3214285714285714, 0.4540059347181009, 0.3424499736597783]","{'snow': ['m0'], 'dry': ['m1'], 'poor_viz': ['m2', 'm3'], 'wet': ['m4']}","{'snow': 1, 'dry': 1, 'poor_viz': 2, 'wet': 1}","{'snow': 0.3735892566479531, 'dry': 0.4230769230769231, 'poor_viz': 0.38771725307333615, 'wet': 0.3424499736597783}",{'poor_viz': 0.4540059347181009},0.261560,0.184742,0.077688,0.276185,0.199825,wet,0.276185,poor_viz,poor_viz,False,False,True,poor_viz,align_mode_maxConf,False,False,2,1,1,1.0,medium,0.199825
1960,1960,2354,2354,innerTrain,NY_840_Westbound_Ramp_NY_5A___New_Hartford__Eastbound__Skyline_2097_2024-02-17-02:00:26.jpg,/home/csutter/cron/data/Skyline_2097/20240217/NY_840_Westbound_Ramp_NY_5A___New_Hartford__Eastbound__Skyline_2097_2024-02-17-02:00:26.jpg,Skyline_2097,dry,0,night,"{Timestamp('2024-02-17 11:27:15.743111'): 'dawn', Timestamp('2024-02-17 11:56:53.298882'): 'sunrise', Timestamp('2024-02-17 22:34:13.229237'): 'sunset', Timestamp('2024-02-17 23:03:52.501291'): 'dusk'}",0.096962,0.036726,0.613636,0.109497,0.143179,0.613636,/home/csutter/cron/data/Skyline_2097/20240217/NY_840_Westbound_Ramp_NY_5A___New_Hartford__Eastbound__Skyline_2097_2024-02-17-02:00:26.jpg,innerTrain,0,43.091908,-75.308290,2024,2,17,20240217,02:00:26,20240217,02:00:26 20240217,2024-02-17 02:00:26,2024-02-17 02:00:00,2024-02-17,0,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t00z_02.parquet,"[43.09732925862063, -75.30698895837469]",0.611516,2024-02-17,2024-02-17 02:00:00,43.097329,-75.306989,269.56964,270.18512,0.00270,268.4373,88.7,2.379694,1.40882,3.605064,0.000298,0.023,157.20090,10.0,101235.0,0.0,281.1,100.0,5301.5490,240.99979,0.0,500.0,2.765451,0.113675,0.043056,0.547042,0.128370,0.167858,snow,0.547042,False,0,0.613636,snow,0.219528,0.154674,0.423077,0.068914,0.133807,0.423077,snow,0.449776,0.298043,0.152364,0.099816,0.000000,0.449776,wet,0.298899,0.138707,0.113717,0.043769,0.404908,0.404908,poor_viz,0.345440,0.154075,0.000000,0.193558,0.306928,0.345440,wet,"['snow', 'snow', 'wet', 'poor_viz', 'wet']","[0.6136363636363636, 0.4230769230769231, 0.4497759555616588, 0.4049079754601227, 0.3454400739549143]","{'snow': ['m0', 'm1'], 'wet': ['m2', 'm4'], 'poor_viz': ['m3']}","{'snow': 2, 'wet': 2, 'poor_viz': 1}","{'snow': 0.5183566433566433, 'wet': 0.39760801475828655, 'poor_viz': 0.4049079754601227}",{'snow': 0.6136363636363636},0.168492,0.260559,0.103111,0.291364,0.176474,wet,0.291364,snow,snow,False,False,True,snow,align_mode_maxConf,False,False,2,1,1,1.0,medium,0.260559
2077,2077,481,481,innerTrain,Route_16_Northbound_at_Emery_Road__Northbound__Skyline_6185_2024-02-17-02:01:13.jpg,/home/csutter/cron/data/Skyline_6185/20240217/Route_16_Northbound_at_Emery_Road__Northbound__Skyline_6185_2024-02-17-02:01:13.jpg,Skyline_6185,dry,0,night,"{Timestamp('2024-02-17 11:39:55.588696'): 'dawn', Timestamp('2024-02-17 12:09:21.688295'): 'sunrise', Timestamp('2024-02-17 22:47:53.541103'): 'sunset', Timestamp('2024-02-17 23:17:21.316518'): 'dusk'}",0.160833,0.018653,0.450000,0.188013,0.182501,0.450000,/home/csutter/cron/data/Skyline_6185/20240217/Route_16_Northbound_at_Emery_Road__Northbound__Skyline_6185_2024-02-17-02:01:13.jpg,innerTrain,0,42.709619,-78.577489,2024,2,17,20240217,02:01:13,20240217,02:01:13 20240217,2024-02-17 02:01:13,2024-02-17 02:00:00,2024-02-17,0,2024,2,17,20240217,/home/csutter/AI2ES/cleaned/HRRR/2024/02/20240217_hrrr.t00z_02.parquet,"[42.705758078261326, -78.59141944925477]",1.219203,2024-02-17,2024-02-17 02:00:00,42.705758,-78.591419,269.69464,271.93512,0.00229,265.9998,76.4,2.379694,1.40882,2.917564,0.000634,0.049,336.20090,0.0,101399.0,0.0,280.9,100.0,5306.2990,242.43729,0.0,500.0,2.765451,0.161003,0.018673,0.449418,0.188212,0.182695,snow,0.449418,False,0,0.450000,snow,0.206576,0.423077,0.156017,0.153847,0.060482,0.423077,dry,0.000000,0.403936,0.204043,0.108486,0.283535,0.403936,dry,0.237621,0.193713,0.142995,0.050671,0.375000,0.375000,poor_viz,0.198436,0.117893,0.333333,0.180906,0.169432,0.333333,snow,"['snow', 'dry', 'dry', 'poor_viz', 'snow']","[0.45, 0.4230769230769231, 0.40393635126796, 0.375, 0.3333333333333333]","{'snow': ['m0', 'm4'], 'dry': ['m1', 'm2'], 'poor_viz': ['m3']}","{'snow': 2, 'dry': 2, 'poor_viz': 1}","{'snow': 0.39166666666666666, 'dry': 0.4135066371724415, 'poor_viz': 0.375}",{'snow': 0.45},0.259890,0.257278,0.136385,0.165027,0.181420,dry,0.259890,snow,snow,False,False,True,snow,align_mode_maxConf,False,False,2,1,1,1.0,medium,0.257278