In [1]:
import pandas as pd
from glob import glob
import os
import sys
cnn_scripts_path = '/home/csutter/DRIVE-clean/CNN/scripts'
sys.path.append(cnn_scripts_path)

pd.set_option('display.max_columns', None)


# imported reusable code from CNN directory
import results_summaries

In [ ]:
/home/csutter/DRIVE-clean/downstream/data_predsFinal

### Data read in

In [16]:
# To see what files match with final versions in IJTST paper: /home/csutter/DRIVE-clean/notebooks/results_for_paper.ipynb

phasecol = "outerPhase" #innerPhase
phasedes = "outerTest" #innerVal

### CNN

# outerTest 68.1
# innerVal 69.1

files_list = glob("/home/csutter/DRIVE-clean/CNN/data_preds/*")
files_list = [x for x in files_list if "A_resnet_TRLETrue_ASTTrue_L20_1_DR0_2_E75_AugTrue" in x]

dfs30 =[]
for f in files_list:
    d = pd.read_csv(f)
    d = d[d[phasecol]==phasedes] 
    dfs30.append(d)

cnn = pd.concat(dfs30).reset_index()

cnn.rename(columns={'model_pred': 'cnn_pred','model_prob': 'cnn_prob'}, inplace=True)

print(len(cnn))
display(cnn.head(4))



### Downstream

files_list = glob("/home/csutter/DRIVE-clean/downstream/data_predsFinal/*")

files_list = [x for x in files_list if "A_resnet_TRLETrue_ASTTrue_L20_1_DR0_2_E75_AugTrue" in x]
print(len(files_list))


# df = pd.read_csv("/home/csutter/DRIVE-clean/downstream/data_results/results_by_exp_innerVal.csv")

dfs30 =[]
for f in files_list:
    filename = os.path.basename(f)
    
    # 1. Find the starting index of "_OT" to be safe
    start_idx = filename.find("_OT")
    
    # 2. Extract exactly 11 characters starting from 'O'
    if start_idx != -1:
        # start_idx + 1 skips the "_", and + 12 grabs the 11 characters after it
        tracker_val = filename[start_idx + 1 : start_idx + 12] 
    else:
        tracker_val = "unknown" 
    
    # 3. Process the CSV
    d = pd.read_csv(f)
    d = d[d[phasecol] == phasedes]
    # d["model_pred"] = d["ds_pred"]
    
    # 4. Assign the tracker value
    d["tracker"] = tracker_val
    
    dfs30.append(d)

ds = pd.concat(dfs30).reset_index()

# ds.rename(columns={'model_pred': 'ds_pred','model_prob': 'ds_prob'}, inplace=True)

print(len(ds))
display(ds.head(4))

# outerTest 80.2
# innerVal 80.7

107445

,index,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,innerPhase,Unnamed: 0,outerPhase,img_name,img_orig,site,img_index,img_cat,foldnum,ID,Latitude,Longitude,date,yr,mo,day,time,yr_mo,timeofday,timeofevent,innerPhaseOrig,prob_dry,prob_poor_viz,prob_snow,prob_snow_severe,prob_wet,cnn_pred,tracker,cnn_prob
0,1774,1774,1774,1774,1774,NAOuterTest,1774,outerTest,"Routes_5,_8,_12_Burrstone_Road_Interchange___U...",/home/csutter/DRIVE/site_analysis/group_labeli...,Skyline_2103,613,wet,2,Skyline_2103,43.092303,-75.262824,1/24/22,2022,1,24,14:00:03,202201,day,"dawn:11:52:42.959980, sunrise:12:24:05.866980,...",NAOuterTest,0.183997,0.000286,0.004217,0.000651,0.810849,wet,OT2_m1_T3V4,0.810849
1,1775,1775,1775,1775,1775,NAOuterTest,1775,outerTest,"Routes_5,_8,_12_Burrstone_Road_Interchange___U...",/home/csutter/DRIVE/site_analysis/group_labeli...,Skyline_2103,614,wet,2,Skyline_2103,43.092303,-75.262824,1/24/22,2022,1,24,15:00:04,202201,day,"dawn:11:52:42.959980, sunrise:12:24:05.866980,...",NAOuterTest,0.263647,0.000303,0.005230,0.000522,0.730298,wet,OT2_m1_T3V4,0.730298
2,1776,1776,1776,1776,1776,NAOuterTest,1776,outerTest,"Routes_5,_8,_12_Burrstone_Road_Interchange___U...",/home/csutter/DRIVE/site_analysis/group_labeli...,Skyline_2103,615,wet,2,Skyline_2103,43.092303,-75.262824,1/24/22,2022,1,24,16:00:03,202201,day,"dawn:11:52:42.959980, sunrise:12:24:05.866980,...",NAOuterTest,0.297113,0.000855,0.054545,0.002325,0.645162,wet,OT2_m1_T3V4,0.645162
3,1777,1777,1777,1777,1777,NAOuterTest,1777,outerTest,"Routes_5,_8,_12_Burrstone_Road_Interchange___U...",/home/csutter/DRIVE/site_analysis/group_labeli...,Skyline_2103,616,dry,2,Skyline_2103,43.092303,-75.262824,1/24/22,2022,1,24,17:00:03,202201,day,"dawn:11:52:42.959980, sunrise:12:24:05.866980,...",NAOuterTest,0.094142,0.000191,0.802262,0.003576,0.099829,snow,OT2_m1_T3V4,0.802262

30
107445

,index,Unnamed: 0.1,innerPhase,outerPhase,img_name,img_orig,site,img_cat,foldnum,timeofday,timeofevent,calib_prob_dry,calib_prob_poor_viz,calib_prob_snow,calib_prob_snow_severe,calib_prob_wet,calib_prob,Unnamed: 0,img_orig_hrrr,img_index,Latitude,Longitude,yr,mo,day,date,time,ymd,date_and_time_str,date_and_time_dt,date_and_time_dt_round,date_and_time_dt_init,init_hr,init_year,init_month,init_day,init_yyyymmdd,hrrr_file,HRRR_latlon,HRRR_distkm,time.1,valid_time,latitude,longitude,t2m,pt,sh2,d2m,r2,u10,v10,si10,asnow,tp,orog,cape,mslma,dswrf,dlwrf,tcc,gh,dpt,atmosphere,isobaricInhPa,uavg,ds_prob_dry,ds_prob_poor_viz,ds_prob_snow,ds_prob_snow_severe,ds_prob_wet,ds_pred,ds_prob,tracker
0,6149,6149,NAOuterTest,outerTest,"NY_5A_at_NY_8,_12_South_Interchange___Utica_(2...",/home/csutter/DRIVE/site_analysis/group_labeli...,Skyline_6390,dry,1,day,"dawn:11:51:53.826190, sunrise:12:23:12.346072,...",0.287433,0.004011,0.065371,0.088519,0.554667,0.554667,6345,/home/csutter/DRIVE/site_analysis/group_labeli...,3758,43.106347,-75.239611,2022,1,25,20220125,14:00:18,20220125,14:00:18 20220125,2022-01-25 14:00:18,2022-01-25 14:00:00,2022-01-25 12:00:00,12,2022,1,25,20220125,/home/csutter/AI2ES/cleaned/HRRR/2022/01/20220...,"[43.11057314057041, -75.22665856772227]",1.15411,2022-01-25 12:00:00,2022-01-25 14:00:00,43.110573,-75.226659,268.92932,269.20520,0.00237,266.72845,82.3,2.262690,0.406258,2.310350,0.000000,0.0,129.91965,0.0,101247.0,229.8,200.0,100.0,5279.0750,215.06229,0.0,500.0,2.298871,0.577144,0.028814,0.016860,0.001627,0.375555,dry,0.577144,OT1_m3_T5V0
1,6150,6150,NAOuterTest,outerTest,"NY_5A_at_NY_8,_12_South_Interchange___Utica_(2...",/home/csutter/DRIVE/site_analysis/group_labeli...,Skyline_6390,dry,1,day,"dawn:11:51:53.826190, sunrise:12:23:12.346072,...",0.411637,0.003206,0.041326,0.030318,0.513514,0.513514,6346,/home/csutter/DRIVE/site_analysis/group_labeli...,3759,43.106347,-75.239611,2022,1,25,20220125,14:04:10,20220125,14:04:10 20220125,2022-01-25 14:04:10,2022-01-25 14:00:00,2022-01-25 12:00:00,12,2022,1,25,20220125,/home/csutter/AI2ES/cleaned/HRRR/2022/01/20220...,"[43.11057314057041, -75.22665856772227]",1.15411,2022-01-25 12:00:00,2022-01-25 14:00:00,43.110573,-75.226659,268.92932,269.20520,0.00237,266.72845,82.3,2.262690,0.406258,2.310350,0.000000,0.0,129.91965,0.0,101247.0,229.8,200.0,100.0,5279.0750,215.06229,0.0,500.0,2.298871,0.625464,0.022625,0.012184,0.001627,0.338100,dry,0.625464,OT1_m3_T5V0
2,6151,6151,NAOuterTest,outerTest,"NY_5A_at_NY_8,_12_South_Interchange___Utica_(2...",/home/csutter/DRIVE/site_analysis/group_labeli...,Skyline_6390,dry,1,day,"dawn:11:51:53.826190, sunrise:12:23:12.346072,...",0.298372,0.005195,0.043598,0.027014,0.625821,0.625821,6347,/home/csutter/DRIVE/site_analysis/group_labeli...,3760,43.106347,-75.239611,2022,1,25,20220125,16:04:02,20220125,16:04:02 20220125,2022-01-25 16:04:02,2022-01-25 16:00:00,2022-01-25 14:00:00,14,2022,1,25,20220125,/home/csutter/AI2ES/cleaned/HRRR/2022/01/20220...,"[43.11057314057041, -75.22665856772227]",1.15411,2022-01-25 14:00:00,2022-01-25 16:00:00,43.110573,-75.226659,270.23320,270.39667,0.00221,265.87964,72.6,4.935690,-0.502047,5.057330,0.000002,0.0,129.91965,20.0,101373.0,395.9,215.6,100.0,5283.2760,213.99979,0.0,500.0,4.961158,0.721890,0.018388,0.010569,0.000000,0.249152,dry,0.721890,OT1_m3_T5V0
3,6152,6152,NAOuterTest,outerTest,"NY_5A_at_NY_8,_12_South_Interchange___Utica_(2...",/home/csutter/DRIVE/site_analysis/group_labeli...,Skyline_6390,snow,1,night,"dawn:11:49:26.004810, sunrise:12:20:29.831166,...",0.443114,0.007113,0.274234,0.194886,0.080653,0.443114,6348,/home/csutter/DRIVE/site_analysis/group_labeli...,3761,43.106347,-75.239611,2022,1,28,20220128,02:00:01,20220128,02:00:01 20220128,2022-01-28 02:00:01,2022-01-28 02:00:00,2022-01-28 00:00:00,0,2022,1,28,20220128,/home/csutter/AI2ES/cleaned/HRRR/2022/01/20220...,"[43.11057314057041, -75.22665856772227]",1.15411,2022-01-28 00:00:00,2022-01-28 02:00:00,43.110573,-75.226659,267.97644,267.78912,0.00175,262.93730,61.4,-1.880116,-1.695648,2.981195,0.000000,0.0,129.91965,0.0,101910.0,0.0,283.1,100.0,5383.2207,234.87479,0.0,500.0,2.531809,0.819519,0.001578,0.049727,0.011749,0.117427,dry,0.819519,OT1_m3_T5V0

In [22]:
# ==========================================
# 3. EXTRACT TRUE PROBS & MERGE
# ==========================================
def get_true_prob_cnn(row):
    return row[f"prob_{row['img_cat']}"]

def get_true_prob_ds(row):
    return row[f"ds_prob_{row['img_cat']}"]

cnn['true_class_prob_cnn'] = cnn.apply(get_true_prob_cnn, axis=1)
ds['true_class_prob_ds'] = ds.apply(get_true_prob_ds, axis=1)

# Merge the explicit dataframes
merged = cnn.merge(
    ds, 
    on=['img_orig', 'tracker', 'img_cat'], 
    how='inner'
)

# Calculate the true probability shift
merged['true_prob_shift'] = merged['true_class_prob_ds'] - merged['true_class_prob_cnn']
print(f"Merged rows: {len(merged)}")


# ==========================================
# 4. SETUP CORRECTNESS FLAGS
# ==========================================
# Now we use the clean column names we established with .rename()
merged['CNN_Correct'] = merged['cnn_pred'] == merged['img_cat']
merged['DS_Correct'] = merged['ds_pred'] == merged['img_cat']

merged['CNN_Result'] = merged['CNN_Correct'].map({True: 'CNN: Correct', False: 'CNN: Incorrect'})
merged['DS_Result'] = merged['DS_Correct'].map({True: 'DS: Correct', False: 'DS: Incorrect'})

row_order = ['CNN: Correct', 'CNN: Incorrect']
col_order = ['DS: Correct', 'DS: Incorrect']


# ==========================================
# 5. MACRO-LEVEL SUMMARIES
# ==========================================

# --- Matrix 1: Counts & Percentages ---
total_obs = len(merged)

def format_counts(x):
    cnt = len(x)
    pct = (cnt / total_obs) * 100
    return f"{cnt} ({pct:.1f}%)"

matrix_1 = merged.groupby(['CNN_Result', 'DS_Result']).apply(format_counts).unstack()
matrix_1 = matrix_1.reindex(index=row_order, columns=col_order)

print("\n=== Matrix 1: Total Observations & Percentages ===")
display(matrix_1)

# --- Alt Matrix 1: Counts & Row Percentages (CNN Baseline) ---
# First, get the raw counts in the correct order

print("When the CNN gets it right, how often does the downstream model preserve that correct answer? When the CNN gets it wrong, how often does the downstream model fix it?")
counts_df = merged.groupby(['CNN_Result', 'DS_Result']).size().unstack(fill_value=0)
counts_df = counts_df.reindex(index=row_order, columns=col_order)

# Calculate the total observations per row (CNN total correct, CNN total incorrect)
row_totals = counts_df.sum(axis=1)

# Define the new column order including the Total column
alt_col_order = ['DS: Correct', 'DS: Incorrect', 'Total (Row)']

# Create an empty dataframe to hold our formatted strings
alt_matrix_1 = pd.DataFrame(index=row_order, columns=alt_col_order)

for row in row_order:
    total = row_totals[row]
    
    # Fill in the standard columns
    for col in col_order:
        count = counts_df.loc[row, col]
        pct = (count / total) * 100 if total > 0 else 0
        alt_matrix_1.loc[row, col] = f"{count} ({pct:.1f}%)"
    
    # Add the explicit Total column at the end
    alt_matrix_1.loc[row, 'Total (Row)'] = f"{total} (100.0%)"

print("\n=== Alt Matrix 1: Counts & ROW Percentages ===")
print("(Percentages sum to 100% horizontally, showing DS performance based on CNN starting point)")
display(alt_matrix_1)

# --- Matrix 2: Average Predicted Probabilities ---
def format_pred_probs(x):
    # Using our cleanly renamed columns here
    cnn_mean = x['cnn_prob'].mean()
    ds_mean = x['ds_prob'].mean()
    return f"CNN: {cnn_mean:.3f} | DS: {ds_mean:.3f}"

matrix_2 = merged.groupby(['CNN_Result', 'DS_Result']).apply(format_pred_probs).unstack()
matrix_2 = matrix_2.reindex(index=row_order, columns=col_order)

print("\n=== Matrix 2: Average Predicted Probabilities ===")
print("(The probability the model assigned to its CHOSEN answer)")
display(matrix_2)


# --- Matrix 3: Average Labeled (True Class) Probabilities ---
def format_true_probs(x):
    cnn_mean = x['true_class_prob_cnn'].mean()
    ds_mean = x['true_class_prob_ds'].mean()
    return f"CNN: {cnn_mean:.3f} | DS: {ds_mean:.3f}"

matrix_3 = merged.groupby(['CNN_Result', 'DS_Result']).apply(format_true_probs).unstack()
matrix_3 = matrix_3.reindex(index=row_order, columns=col_order)

print("\n=== Matrix 3: Average Labeled (True Class) Probabilities ===")
print("(The probability the model assigned to the CORRECT answer)")
display(matrix_3)


# ==========================================
# 6. CLASS-LEVEL SUMMARIES
# ==========================================

# --- Determine Transition States ---
def determine_transition(row):
    if not row['CNN_Correct'] and row['DS_Correct']:
        return '1_Rescued (CNN Wrong -> DS Right)'
    elif row['CNN_Correct'] and not row['DS_Correct']:
        return '2_Ruined (CNN Right -> DS Wrong)'
    elif row['CNN_Correct'] and row['DS_Correct']:
        return '3_Agreed (Correct)'
    else:
        return '4_Agreed (Incorrect)'

merged['transition_state'] = merged.apply(determine_transition, axis=1)

# --- Matrix 4: Rescued vs. Ruined Impact by Class ---
base_counts = merged.groupby(['img_cat', 'transition_state']).size().unstack(fill_value=0)
rescue_col = '1_Rescued (CNN Wrong -> DS Right)'
ruin_col = '2_Ruined (CNN Right -> DS Wrong)'

for col in [rescue_col, ruin_col]:
    if col not in base_counts.columns:
        base_counts[col] = 0

class_totals = base_counts.sum(axis=1)
changed_totals = base_counts[rescue_col] + base_counts[ruin_col]
changed_totals_safe = changed_totals.replace(0, np.nan)

rescue_pct_class = (base_counts[rescue_col] / class_totals) * 100
ruin_pct_class = (base_counts[ruin_col] / class_totals) * 100
rescue_pct_change = (base_counts[rescue_col] / changed_totals_safe) * 100
ruin_pct_change = (base_counts[ruin_col] / changed_totals_safe) * 100

impact_matrix = pd.DataFrame({
    'Total Class Images': class_totals,
    'Rescued Count': base_counts[rescue_col],
    'Ruined Count': base_counts[ruin_col],
    '% of Class Rescued': rescue_pct_class.map('{:.1f}%'.format),
    '% of Class Ruined': ruin_pct_class.map('{:.1f}%'.format),
    'Change Win Rate (Rescued)': rescue_pct_change.fillna(0).map('{:.1f}%'.format),
    'Change Loss Rate (Ruined)': ruin_pct_change.fillna(0).map('{:.1f}%'.format)
})

print("\n=== Matrix 4: Rescued vs. Ruined Impact by Class ===")
display(impact_matrix)

# ==========================================
# 7. SPECIFIC DOMAIN: CNN INCORRECT ONLY
# ==========================================

# --- Matrix 5: Class-Level Rescue Rate ---
# Filter the domain to ONLY cases where the CNN guessed incorrectly
cnn_wrong_df = merged[merged['CNN_Correct'] == False]

# Get the raw counts grouped by image category (rows) and DS result (columns)
counts_df = cnn_wrong_df.groupby(['img_cat', 'DS_Result']).size().unstack(fill_value=0)

# Ensure both DS columns exist just in case a category had 0 for one of them
for col in ['DS: Correct', 'DS: Incorrect']:
    if col not in counts_df.columns:
        counts_df[col] = 0

# Calculate the total CNN errors for each category
row_totals = counts_df.sum(axis=1)

# Define the display columns
display_cols = ['DS: Correct (Rescued)', 'DS: Incorrect (Still Wrong)', 'Total CNN Errors (Row)']

# Create an empty dataframe to hold our formatted strings
matrix_5 = pd.DataFrame(index=counts_df.index, columns=display_cols)

for row in counts_df.index:
    total = row_totals[row]
    
    # Format DS: Correct (The Rescue Rate)
    count_correct = counts_df.loc[row, 'DS: Correct']
    pct_correct = (count_correct / total) * 100 if total > 0 else 0
    matrix_5.loc[row, 'DS: Correct (Rescued)'] = f"{count_correct} ({pct_correct:.1f}%)"
    
    # Format DS: Incorrect (The Unfixed Errors)
    count_incorrect = counts_df.loc[row, 'DS: Incorrect']
    pct_incorrect = (count_incorrect / total) * 100 if total > 0 else 0
    matrix_5.loc[row, 'DS: Incorrect (Still Wrong)'] = f"{count_incorrect} ({pct_incorrect:.1f}%)"
    
    # Add the explicit Total column at the end
    matrix_5.loc[row, 'Total CNN Errors (Row)'] = f"{total} (100.0%)"

print("\n=== Matrix 5: Class-Level Rescue Rate (Domain: CNN Incorrect Only) ===")
print("(Percentages sum to 100% horizontally. Shows exactly what happened to the errors the CNN made.)")
display(matrix_5)

# ==========================================
# 8. SPECIFIC DOMAIN: CNN CORRECT ONLY
# ==========================================

# --- Matrix 6: Class-Level Ruin Rate ---
# Filter the domain to ONLY cases where the CNN guessed correctly
cnn_correct_df = merged[merged['CNN_Correct'] == True]

# Get the raw counts grouped by image category (rows) and DS result (columns)
counts_df_correct = cnn_correct_df.groupby(['img_cat', 'DS_Result']).size().unstack(fill_value=0)

# Ensure both DS columns exist just in case a category had 0 for one of them
for col in ['DS: Correct', 'DS: Incorrect']:
    if col not in counts_df_correct.columns:
        counts_df_correct[col] = 0

# Calculate the total CNN correct predictions for each category
row_totals_correct = counts_df_correct.sum(axis=1)

# Define the display columns
display_cols_correct = ['DS: Correct (Preserved)', 'DS: Incorrect (Ruined)', 'Total CNN Correct (Row)']

# Create an empty dataframe to hold our formatted strings
matrix_6 = pd.DataFrame(index=counts_df_correct.index, columns=display_cols_correct)

for row in counts_df_correct.index:
    total = row_totals_correct[row]
    
    # Format DS: Correct (The Preserved Rate)
    count_correct = counts_df_correct.loc[row, 'DS: Correct']
    pct_correct = (count_correct / total) * 100 if total > 0 else 0
    matrix_6.loc[row, 'DS: Correct (Preserved)'] = f"{count_correct} ({pct_correct:.1f}%)"
    
    # Format DS: Incorrect (The Ruin Rate)
    count_incorrect = counts_df_correct.loc[row, 'DS: Incorrect']
    pct_incorrect = (count_incorrect / total) * 100 if total > 0 else 0
    matrix_6.loc[row, 'DS: Incorrect (Ruined)'] = f"{count_incorrect} ({pct_incorrect:.1f}%)"
    
    # Add the explicit Total column at the end
    matrix_6.loc[row, 'Total CNN Correct (Row)'] = f"{total} (100.0%)"

print("\n=== Matrix 6: Class-Level Ruin Rate (Domain: CNN Correct Only) ===")
print("(Percentages sum to 100% horizontally. Shows exactly what happened to the accurate CNN predictions.)")
display(matrix_6)


# ==========================================
# 9. OVERALL TRANSITION IMPACT BY CLASS
# ==========================================

# --- Matrix 7: Full Transition Breakdown by Class ---
# Get the raw counts grouped by image category and transition state
counts_df_all = merged.groupby(['img_cat', 'transition_state']).size().unstack(fill_value=0)

# Map our technical transition state names to the clean names you requested
col_mapping = {
    '3_Agreed (Correct)': 'Unchanged (Correct)',
    '4_Agreed (Incorrect)': 'Unchanged (Incorrect)',
    '1_Rescued (CNN Wrong -> DS Right)': 'Rescued',
    '2_Ruined (CNN Right -> DS Wrong)': 'Ruined'
}

# Rename the columns in the counts dataframe
counts_df_all = counts_df_all.rename(columns=col_mapping)

# Ensure all 4 columns exist even if a category had 0 in one of them
expected_cols = ['Unchanged (Correct)', 'Unchanged (Incorrect)', 'Rescued', 'Ruined']
for col in expected_cols:
    if col not in counts_df_all.columns:
        counts_df_all[col] = 0

# Reorder columns to exactly match your request
counts_df_all = counts_df_all[expected_cols]

# Calculate the total images for each category (row totals)
row_totals_all = counts_df_all.sum(axis=1)

# Create an empty dataframe to hold our formatted strings
matrix_7 = pd.DataFrame(index=counts_df_all.index)

for row in counts_df_all.index:
    total = row_totals_all[row]
    
    # Format each of the 4 columns
    for col in expected_cols:
        count = counts_df_all.loc[row, col]
        pct = (count / total) * 100 if total > 0 else 0
        matrix_7.loc[row, col] = f"{count} ({pct:.1f}%)"
    
    # Add the explicit Total column at the end
    matrix_7.loc[row, 'Total Images (Row)'] = f"{total} (100.0%)"

print("\n=== Matrix 7: Full Transition Breakdown by Class ===")
print("(Percentages sum to 100% horizontally. Shows exactly what happened to EVERY image in the category.)")
display(matrix_7)

Merged rows: 107445

=== Matrix 1: Total Observations & Percentages ===

DS_Result         DS: Correct  DS: Incorrect
CNN_Result
CNN: Correct    66841 (62.2%)    6278 (5.8%)
CNN: Incorrect  19373 (18.0%)  14953 (13.9%)

When the CNN gets it right, how often does the downstream model preserve that correct answer? When the CNN gets it wrong, how often does the downstream model fix it?

=== Alt Matrix 1: Counts & ROW Percentages ===
(Percentages sum to 100% horizontally, showing DS performance based on CNN starting point)

                  DS: Correct  DS: Incorrect     Total (Row)
CNN: Correct    66841 (91.4%)    6278 (8.6%)  73119 (100.0%)
CNN: Incorrect  19373 (56.4%)  14953 (43.6%)  34326 (100.0%)

=== Matrix 2: Average Predicted Probabilities ===
(The probability the model assigned to its CHOSEN answer)

DS_Result                  DS: Correct           DS: Incorrect
CNN_Result
CNN: Correct    CNN: 0.766 | DS: 0.847  CNN: 0.617 | DS: 0.572
CNN: Incorrect  CNN: 0.595 | DS: 0.697  CNN: 0.658 | DS: 0.639

=== Matrix 3: Average Labeled (True Class) Probabilities ===
(The probability the model assigned to the CORRECT answer)

DS_Result                  DS: Correct           DS: Incorrect
CNN_Result
CNN: Correct    CNN: 0.766 | DS: 0.847  CNN: 0.617 | DS: 0.298
CNN: Incorrect  CNN: 0.262 | DS: 0.697  CNN: 0.180 | DS: 0.219

=== Matrix 4: Rescued vs. Ruined Impact by Class ===

,Total Class Images,Rescued Count,Ruined Count,% of Class Rescued,% of Class Ruined,Change Win Rate (Rescued),Change Loss Rate (Ruined)
img_cat,,,,,,,
dry,38000,9787,1096,25.8%,2.9%,89.9%,10.1%
poor_viz,4575,378,478,8.3%,10.4%,44.2%,55.8%
snow,14945,2876,688,19.2%,4.6%,80.7%,19.3%
snow_severe,7635,656,430,8.6%,5.6%,60.4%,39.6%
wet,42290,5676,3586,13.4%,8.5%,61.3%,38.7%

=== Matrix 5: Class-Level Rescue Rate (Domain: CNN Incorrect Only) ===
(Percentages sum to 100% horizontally. Shows exactly what happened to the errors the CNN made.)

,DS: Correct (Rescued),DS: Incorrect (Still Wrong),Total CNN Errors (Row)
img_cat,,,
dry,9787 (75.2%),3222 (24.8%),13009 (100.0%)
poor_viz,378 (33.1%),765 (66.9%),1143 (100.0%)
snow,2876 (47.8%),3136 (52.2%),6012 (100.0%)
snow_severe,656 (37.6%),1087 (62.4%),1743 (100.0%)
wet,5676 (45.7%),6743 (54.3%),12419 (100.0%)

=== Matrix 6: Class-Level Ruin Rate (Domain: CNN Correct Only) ===
(Percentages sum to 100% horizontally. Shows exactly what happened to the accurate CNN predictions.)

,DS: Correct (Preserved),DS: Incorrect (Ruined),Total CNN Correct (Row)
img_cat,,,
dry,23895 (95.6%),1096 (4.4%),24991 (100.0%)
poor_viz,2954 (86.1%),478 (13.9%),3432 (100.0%)
snow,8245 (92.3%),688 (7.7%),8933 (100.0%)
snow_severe,5462 (92.7%),430 (7.3%),5892 (100.0%)
wet,26285 (88.0%),3586 (12.0%),29871 (100.0%)

=== Matrix 7: Full Transition Breakdown by Class ===
(Percentages sum to 100% horizontally. Shows exactly what happened to EVERY image in the category.)

,Unchanged (Correct),Unchanged (Incorrect),Rescued,Ruined,Total Images (Row)
img_cat,,,,,
dry,23895 (62.9%),3222 (8.5%),9787 (25.8%),1096 (2.9%),38000 (100.0%)
poor_viz,2954 (64.6%),765 (16.7%),378 (8.3%),478 (10.4%),4575 (100.0%)
snow,8245 (55.2%),3136 (21.0%),2876 (19.2%),688 (4.6%),14945 (100.0%)
snow_severe,5462 (71.5%),1087 (14.2%),656 (8.6%),430 (5.6%),7635 (100.0%)
wet,26285 (62.2%),6743 (15.9%),5676 (13.4%),3586 (8.5%),42290 (100.0%)

In [24]:
import pandas as pd
import numpy as np

# ==========================================
# 3. EXTRACT TRUE PROBS & MERGE
# ==========================================
def get_true_prob_cnn(row):
    return row[f"prob_{row['img_cat']}"]

def get_true_prob_ds(row):
    return row[f"ds_prob_{row['img_cat']}"]

cnn['true_class_prob_cnn'] = cnn.apply(get_true_prob_cnn, axis=1)
ds['true_class_prob_ds'] = ds.apply(get_true_prob_ds, axis=1)

# Merge the explicit dataframes
merged = cnn.merge(
    ds, 
    on=['img_orig', 'tracker', 'img_cat'], 
    how='inner'
)

# Calculate the true probability shift
merged['true_prob_shift'] = merged['true_class_prob_ds'] - merged['true_class_prob_cnn']
print(f"Merged rows: {len(merged)}")


# ==========================================
# 4. SETUP CORRECTNESS FLAGS
# ==========================================
# Now we use the clean column names we established with .rename()
merged['CNN_Correct'] = merged['cnn_pred'] == merged['img_cat']
merged['RF_Correct'] = merged['ds_pred'] == merged['img_cat']

merged['CNN_Result'] = merged['CNN_Correct'].map({True: 'CNN: Correct', False: 'CNN: Incorrect'})
merged['RF_Result'] = merged['RF_Correct'].map({True: 'RF: Correct', False: 'RF: Incorrect'})

row_order = ['CNN: Correct', 'CNN: Incorrect']
col_order = ['RF: Correct', 'RF: Incorrect']

# Set desired order for image categories
cat_order = ['snow_severe', 'snow', 'wet', 'dry', 'poor_viz']


# ==========================================
# 5. MACRO-LEVEL SUMMARIES
# ==========================================

# --- Matrix 1: Percentages Only ---
total_obs = len(merged)

def format_counts_pct(x):
    cnt = len(x)
    pct = (cnt / total_obs) * 100
    return f"{pct:.1f}%"

matrix_1 = merged.groupby(['CNN_Result', 'RF_Result']).apply(format_counts_pct).unstack()
matrix_1 = matrix_1.reindex(index=row_order, columns=col_order)

print("\n=== Matrix 1: Total Observations Percentages ===")
display(matrix_1)

# --- Alt Matrix 1: Row Percentages (CNN Baseline) ---
counts_df = merged.groupby(['CNN_Result', 'RF_Result']).size().unstack(fill_value=0)
counts_df = counts_df.reindex(index=row_order, columns=col_order)

row_totals = counts_df.sum(axis=1)
alt_col_order = ['RF: Correct', 'RF: Incorrect', 'Total (Row)']

alt_matrix_1 = pd.DataFrame(index=row_order, columns=alt_col_order)

for row in row_order:
    total = row_totals[row]
    for col in col_order:
        count = counts_df.loc[row, col]
        pct = (count / total) * 100 if total > 0 else 0
        alt_matrix_1.loc[row, col] = f"{pct:.1f}%"
    
    alt_matrix_1.loc[row, 'Total (Row)'] = "100.0%"

print("\n=== Alt Matrix 1: ROW Percentages Only ===")
print("(Percentages sum to 100% horizontally, showing RF performance based on CNN starting point)")
display(alt_matrix_1)


# ==========================================
# 6. SPECIFIC DOMAIN: CNN INCORRECT ONLY
# ==========================================

# --- Matrix 5: Class-Level Rescue Rate ---
cnn_wrong_df = merged[merged['CNN_Correct'] == False]
counts_df = cnn_wrong_df.groupby(['img_cat', 'RF_Result']).size().unstack(fill_value=0)

for col in ['RF: Correct', 'RF: Incorrect']:
    if col not in counts_df.columns:
        counts_df[col] = 0

# Reorder the rows to match the requested category order
counts_df = counts_df.reindex(cat_order, fill_value=0)

row_totals = counts_df.sum(axis=1)
display_cols = ['RF: Correct (Rescued)', 'RF: Incorrect (Still Wrong)', 'Total CNN Errors (Row)']

matrix_5 = pd.DataFrame(index=counts_df.index, columns=display_cols)

for row in counts_df.index:
    total = row_totals[row]
    
    count_correct = counts_df.loc[row, 'RF: Correct']
    pct_correct = (count_correct / total) * 100 if total > 0 else 0
    matrix_5.loc[row, 'RF: Correct (Rescued)'] = f"{pct_correct:.1f}%"
    
    count_incorrect = counts_df.loc[row, 'RF: Incorrect']
    pct_incorrect = (count_incorrect / total) * 100 if total > 0 else 0
    matrix_5.loc[row, 'RF: Incorrect (Still Wrong)'] = f"{pct_incorrect:.1f}%"
    
    # Only tag 100% if there were actually errors to calculate
    matrix_5.loc[row, 'Total CNN Errors (Row)'] = "100.0%" if total > 0 else "0.0%"

print("\n=== Matrix 5: Class-Level Rescue Rate (Domain: CNN Incorrect Only) ===")
print("(Percentages sum to 100% horizontally. Shows exactly what happened to the errors the CNN made.)")
display(matrix_5)


# ==========================================
# 7. SPECIFIC DOMAIN: CNN CORRECT ONLY
# ==========================================

# --- Matrix 6: Class-Level Ruin Rate ---
cnn_correct_df = merged[merged['CNN_Correct'] == True]
counts_df_correct = cnn_correct_df.groupby(['img_cat', 'RF_Result']).size().unstack(fill_value=0)

for col in ['RF: Correct', 'RF: Incorrect']:
    if col not in counts_df_correct.columns:
        counts_df_correct[col] = 0

# Reorder the rows to match the requested category order
counts_df_correct = counts_df_correct.reindex(cat_order, fill_value=0)

row_totals_correct = counts_df_correct.sum(axis=1)
display_cols_correct = ['RF: Correct (Preserved)', 'RF: Incorrect (Ruined)', 'Total CNN Correct (Row)']

matrix_6 = pd.DataFrame(index=counts_df_correct.index, columns=display_cols_correct)

for row in counts_df_correct.index:
    total = row_totals_correct[row]
    
    count_correct = counts_df_correct.loc[row, 'RF: Correct']
    pct_correct = (count_correct / total) * 100 if total > 0 else 0
    matrix_6.loc[row, 'RF: Correct (Preserved)'] = f"{pct_correct:.1f}%"
    
    count_incorrect = counts_df_correct.loc[row, 'RF: Incorrect']
    pct_incorrect = (count_incorrect / total) * 100 if total > 0 else 0
    matrix_6.loc[row, 'RF: Incorrect (Ruined)'] = f"{pct_incorrect:.1f}%"
    
    matrix_6.loc[row, 'Total CNN Correct (Row)'] = "100.0%" if total > 0 else "0.0%"

print("\n=== Matrix 6: Class-Level Ruin Rate (Domain: CNN Correct Only) ===")
print("(Percentages sum to 100% horizontally. Shows exactly what happened to the accurate CNN predictions.)")
display(matrix_6)


# ==========================================
# 8. OVERALL TRANSITION IMPACT BY CLASS
# ==========================================

# --- Determine Transition States First ---
def determine_transition(row):
    if not row['CNN_Correct'] and row['RF_Correct']:
        return '1_Rescued (CNN Wrong -> RF Right)'
    elif row['CNN_Correct'] and not row['RF_Correct']:
        return '2_Ruined (CNN Right -> RF Wrong)'
    elif row['CNN_Correct'] and row['RF_Correct']:
        return '3_Agreed (Correct)'
    else:
        return '4_Agreed (Incorrect)'

merged['transition_state'] = merged.apply(determine_transition, axis=1)

# --- Matrix 7: Full Transition Breakdown by Class ---
counts_df_all = merged.groupby(['img_cat', 'transition_state']).size().unstack(fill_value=0)

col_mapping = {
    '3_Agreed (Correct)': 'Unchanged (Correct)',
    '4_Agreed (Incorrect)': 'Unchanged (Incorrect)',
    '1_Rescued (CNN Wrong -> RF Right)': 'Rescued',
    '2_Ruined (CNN Right -> RF Wrong)': 'Ruined'
}

counts_df_all = counts_df_all.rename(columns=col_mapping)

expected_cols = ['Unchanged (Correct)', 'Unchanged (Incorrect)', 'Rescued', 'Ruined']
for col in expected_cols:
    if col not in counts_df_all.columns:
        counts_df_all[col] = 0

counts_df_all = counts_df_all[expected_cols]

# Reorder the rows to match the requested category order
counts_df_all = counts_df_all.reindex(cat_order, fill_value=0)

row_totals_all = counts_df_all.sum(axis=1)
matrix_7 = pd.DataFrame(index=counts_df_all.index)

for row in counts_df_all.index:
    total = row_totals_all[row]
    for col in expected_cols:
        count = counts_df_all.loc[row, col]
        pct = (count / total) * 100 if total > 0 else 0
        matrix_7.loc[row, col] = f"{pct:.1f}%"
    
    matrix_7.loc[row, 'Total Images (Row)'] = "100.0%" if total > 0 else "0.0%"

print("\n=== Matrix 7: Full Transition Breakdown by Class ===")
print("(Percentages sum to 100% horizontally. Shows exactly what happened to EVERY image in the category.)")
display(matrix_7)

Merged rows: 107445

=== Matrix 1: Total Observations Percentages ===

RF_Result      RF: Correct RF: Incorrect
CNN_Result
CNN: Correct         62.2%          5.8%
CNN: Incorrect       18.0%         13.9%

=== Alt Matrix 1: ROW Percentages Only ===
(Percentages sum to 100% horizontally, showing RF performance based on CNN starting point)

               RF: Correct RF: Incorrect Total (Row)
CNN: Correct         91.4%          8.6%      100.0%
CNN: Incorrect       56.4%         43.6%      100.0%

=== Matrix 5: Class-Level Rescue Rate (Domain: CNN Incorrect Only) ===
(Percentages sum to 100% horizontally. Shows exactly what happened to the errors the CNN made.)

,RF: Correct (Rescued),RF: Incorrect (Still Wrong),Total CNN Errors (Row)
img_cat,,,
snow_severe,37.6%,62.4%,100.0%
snow,47.8%,52.2%,100.0%
wet,45.7%,54.3%,100.0%
dry,75.2%,24.8%,100.0%
poor_viz,33.1%,66.9%,100.0%

=== Matrix 6: Class-Level Ruin Rate (Domain: CNN Correct Only) ===
(Percentages sum to 100% horizontally. Shows exactly what happened to the accurate CNN predictions.)

,RF: Correct (Preserved),RF: Incorrect (Ruined),Total CNN Correct (Row)
img_cat,,,
snow_severe,92.7%,7.3%,100.0%
snow,92.3%,7.7%,100.0%
wet,88.0%,12.0%,100.0%
dry,95.6%,4.4%,100.0%
poor_viz,86.1%,13.9%,100.0%

=== Matrix 7: Full Transition Breakdown by Class ===
(Percentages sum to 100% horizontally. Shows exactly what happened to EVERY image in the category.)

,Unchanged (Correct),Unchanged (Incorrect),Rescued,Ruined,Total Images (Row)
img_cat,,,,,
snow_severe,71.5%,14.2%,8.6%,5.6%,100.0%
snow,55.2%,21.0%,19.2%,4.6%,100.0%
wet,62.2%,15.9%,13.4%,8.5%,100.0%
dry,62.9%,8.5%,25.8%,2.9%,100.0%
poor_viz,64.6%,16.7%,8.3%,10.4%,100.0%

# OLD CODE

In [11]:
# Prep data


# --- Step 0: Data Preparation & Extracting True Class Probabilities ---

# print(cnn.columns)
# print(ds.columns)

# Helper functions to grab the probability of the true labeled class (img_cat)
def get_true_prob_cnn(row):
    col_name = f"prob_{row['img_cat']}"
    return row[col_name]

def get_true_prob_ds(row):
    col_name = f"ds_prob_{row['img_cat']}"
    return row[col_name]

# Apply the functions to create a standardized 'true_class_prob' column in both
cnn['true_class_prob'] = cnn.apply(get_true_prob_cnn, axis=1)
ds['true_class_prob'] = ds.apply(get_true_prob_ds, axis=1)

# Merge on unique identifiers, including 'img_cat' so it doesn't get duplicated
merged = cnn.merge(
    ds, 
    on=['img_orig', 'tracker', 'img_cat'], 
    how='inner', 
    suffixes=('_cnn', '_ds')
)

# Calculate the shift in true class probability (Positive = Weather data helped)
merged['true_prob_shift'] = merged['true_class_prob_ds'] - merged['true_class_prob_cnn']

In [10]:
for i in merged.columns:
    print(i)

index_cnn
Unnamed: 0.4
Unnamed: 0.3
Unnamed: 0.2
Unnamed: 0.1_cnn
innerPhase_cnn
Unnamed: 0_cnn
outerPhase_cnn
img_name_cnn
img_orig
site_cnn
img_index_cnn
img_cat
foldnum_cnn
ID
Latitude_cnn
Longitude_cnn
date_cnn
yr_cnn
mo_cnn
day_cnn
time_cnn
yr_mo
timeofday_cnn
timeofevent_cnn
innerPhaseOrig
prob_dry
prob_poor_viz
prob_snow
prob_snow_severe
prob_wet
cnn_pred
tracker
cnn_prob
true_class_prob_cnn
index_ds
Unnamed: 0.1_ds
innerPhase_ds
outerPhase_ds
img_name_ds
site_ds
foldnum_ds
timeofday_ds
timeofevent_ds
calib_prob_dry
calib_prob_poor_viz
calib_prob_snow
calib_prob_snow_severe
calib_prob_wet
calib_prob
Unnamed: 0_ds
img_orig_hrrr
img_index_ds
Latitude_ds
Longitude_ds
yr_ds
mo_ds
day_ds
date_ds
time_ds
ymd
date_and_time_str
date_and_time_dt
date_and_time_dt_round
date_and_time_dt_init
init_hr
init_year
init_month
init_day
init_yyyymmdd
hrrr_file
HRRR_latlon
HRRR_distkm
time.1
valid_time
latitude
longitude
t2m
pt
sh2
d2m
r2
u10
v10
si10
asnow
tp
orog
cape
mslma
dswrf
dlwrf
tcc
gh
dpt
atmosphere
isobaricInhPa
uavg
ds_prob_dry
ds_prob_poor_viz
ds_prob_snow
ds_prob_snow_severe
ds_prob_wet
ds_pred
ds_prob
ds_pred
true_class_prob_ds
true_prob_shift

In [14]:
import pandas as pd
import numpy as np

# ==========================================
# 0. SETUP & CORRECTNESS FLAGS
# ==========================================

# Define Correctness based on the specific '_cnn' and '_ds' columns
merged['CNN_Correct'] = merged['cnn_pred'] == merged['img_cat']
merged['DS_Correct'] = merged['ds_pred'] == merged['img_cat']

# Map booleans to explicit strings for cleaner matrix labels
merged['CNN_Result'] = merged['CNN_Correct'].map({True: 'CNN: Correct', False: 'CNN: Incorrect'})
merged['DS_Result'] = merged['DS_Correct'].map({True: 'DS: Correct', False: 'DS: Incorrect'})

row_order = ['CNN: Correct', 'CNN: Incorrect']
col_order = ['DS: Correct', 'DS: Incorrect']


# ==========================================
# MACRO-LEVEL SUMMARIES
# ==========================================

# --- Matrix 1: Counts & Percentages ---
total_obs = len(merged)

def format_counts(x):
    cnt = len(x)
    pct = (cnt / total_obs) * 100
    return f"{cnt} ({pct:.1f}%)"

matrix_1 = merged.groupby(['CNN_Result', 'DS_Result']).apply(format_counts).unstack()
matrix_1 = matrix_1.reindex(index=row_order, columns=col_order)

print("=== Matrix 1: Total Observations & Percentages ===")
display(matrix_1)


# --- Matrix 2: Average Predicted Probabilities ---
def format_pred_probs(x):
    cnn_mean = x['model_prob'].mean()
    ds_mean = x['ds_prob'].mean()
    return f"CNN: {cnn_mean:.3f} | DS: {ds_mean:.3f}"

matrix_2 = merged.groupby(['CNN_Result', 'DS_Result']).apply(format_pred_probs).unstack()
matrix_2 = matrix_2.reindex(index=row_order, columns=col_order)

print("\n=== Matrix 2: Average Predicted Probabilities ===")
print("(The probability the model assigned to its CHOSEN answer)")
display(matrix_2)


# --- Matrix 3: Average Labeled (True Class) Probabilities ---
def format_true_probs(x):
    cnn_mean = x['true_class_prob_cnn'].mean()
    ds_mean = x['true_class_prob_ds'].mean()
    return f"CNN: {cnn_mean:.3f} | DS: {ds_mean:.3f}"

matrix_3 = merged.groupby(['CNN_Result', 'DS_Result']).apply(format_true_probs).unstack()
matrix_3 = matrix_3.reindex(index=row_order, columns=col_order)

print("\n=== Matrix 3: Average Labeled (True Class) Probabilities ===")
print("(The probability the model assigned to the CORRECT answer)")
display(matrix_3)


# ==========================================
# CLASS-LEVEL SUMMARIES
# ==========================================

# --- Determine Transition States ---
def determine_transition(row):
    if not row['CNN_Correct'] and row['DS_Correct']:
        return '1_Rescued (CNN Wrong -> DS Right)'
    elif row['CNN_Correct'] and not row['DS_Correct']:
        return '2_Ruined (CNN Right -> DS Wrong)'
    elif row['CNN_Correct'] and row['DS_Correct']:
        return '3_Agreed (Correct)'
    else:
        return '4_Agreed (Incorrect)'

merged['transition_state'] = merged.apply(determine_transition, axis=1)

# --- Matrix 4: Rescued vs. Ruined Impact by Class ---
base_counts = merged.groupby(['img_cat', 'transition_state']).size().unstack(fill_value=0)
rescue_col = '1_Rescued (CNN Wrong -> DS Right)'
ruin_col = '2_Ruined (CNN Right -> DS Wrong)'

# Ensure columns exist to prevent KeyErrors if there are 0 rescues/ruins
for col in [rescue_col, ruin_col]:
    if col not in base_counts.columns:
        base_counts[col] = 0

class_totals = base_counts.sum(axis=1)
changed_totals = base_counts[rescue_col] + base_counts[ruin_col]

# Avoid division by zero by replacing 0s with NaNs temporarily
changed_totals_safe = changed_totals.replace(0, np.nan)

rescue_pct_class = (base_counts[rescue_col] / class_totals) * 100
ruin_pct_class = (base_counts[ruin_col] / class_totals) * 100
rescue_pct_change = (base_counts[rescue_col] / changed_totals_safe) * 100
ruin_pct_change = (base_counts[ruin_col] / changed_totals_safe) * 100

impact_matrix = pd.DataFrame({
    'Total Class Images': class_totals,
    'Rescued Count': base_counts[rescue_col],
    'Ruined Count': base_counts[ruin_col],
    '% of Class Rescued': rescue_pct_class.map('{:.1f}%'.format),
    '% of Class Ruined': ruin_pct_class.map('{:.1f}%'.format),
    'Change Win Rate (Rescued)': rescue_pct_change.fillna(0).map('{:.1f}%'.format),
    'Change Loss Rate (Ruined)': ruin_pct_change.fillna(0).map('{:.1f}%'.format)
})

print("\n=== Matrix 4: Rescued vs. Ruined Impact by Class ===")
display(impact_matrix)

/tmp/tmp.IDwB8fmNp5/ipykernel_3355665/4086015077.py:10: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  merged['DS_Correct'] = merged['ds_pred'] == merged['img_cat']

TypeError: '<' not supported between instances of 'str' and 'int'

In [5]:
cnn.columns

Index(['index', 'Unnamed: 0.4', 'Unnamed: 0.3', 'Unnamed: 0.2', 'Unnamed: 0.1',
       'innerPhase', 'Unnamed: 0', 'outerPhase', 'img_name', 'img_orig',
       'site', 'img_index', 'img_cat', 'foldnum', 'ID', 'Latitude',
       'Longitude', 'date', 'yr', 'mo', 'day', 'time', 'yr_mo', 'timeofday',
       'timeofevent', 'innerPhaseOrig', 'prob_dry', 'prob_poor_viz',
       'prob_snow', 'prob_snow_severe', 'prob_wet', 'model_pred', 'tracker',
       'model_prob'],
      dtype='object')

In [13]:
ds.columns

Index(['index', 'Unnamed: 0.1', 'innerPhase', 'outerPhase', 'img_name',
       'img_orig', 'site', 'img_cat', 'foldnum', 'timeofday', 'timeofevent',
       'calib_prob_dry', 'calib_prob_poor_viz', 'calib_prob_snow',
       'calib_prob_snow_severe', 'calib_prob_wet', 'calib_prob', 'Unnamed: 0',
       'img_orig_hrrr', 'img_index', 'Latitude', 'Longitude', 'yr', 'mo',
       'day', 'date', 'time', 'ymd', 'date_and_time_str', 'date_and_time_dt',
       'date_and_time_dt_round', 'date_and_time_dt_init', 'init_hr',
       'init_year', 'init_month', 'init_day', 'init_yyyymmdd', 'hrrr_file',
       'HRRR_latlon', 'HRRR_distkm', 'time.1', 'valid_time', 'latitude',
       'longitude', 't2m', 'pt', 'sh2', 'd2m', 'r2', 'u10', 'v10', 'si10',
       'asnow', 'tp', 'orog', 'cape', 'mslma', 'dswrf', 'dlwrf', 'tcc', 'gh',
       'dpt', 'atmosphere', 'isobaricInhPa', 'uavg', 'ds_prob_dry',
       'ds_prob_poor_viz', 'ds_prob_snow', 'ds_prob_snow_severe',
       'ds_prob_wet', 'ds_pred', 'ds_prob', 'model_pred', 'tracker'],
      dtype='object')

In [12]:
# check uniqueness by img_name and tracker

print(len(cnn[['img_name', 'tracker']].drop_duplicates()))
print(len(ds[['img_name', 'tracker']].drop_duplicates()))

107445
107445

### Notes

For analysis to show weather contributioin, have to compare CNN results which are uniue by img name AND tracker (which is a unique CNN model) to the analagous prediction from the unique img name AND tracker from the unique downstream model. 
- From analysis for response to reviewers (in response to "did we quantify forecast error"): https://docs.google.com/spreadsheets/d/1nOaePktsJAjBDwXAq81lhgnUwCBggr7cy0xNXDVd_20/edit?gid=0#gid=0

Note for tracking past analyses:
- Improvements from CNN to Final model (discussed in IJTST paper, e.g., this text "The final model improves predictions compared to the CNN alone, and the most significant improvements are in the snow and dry classes, which increase by 17.3 and 24.3 percentage points, respectively.") Those numbers are compiled from CF summaries in here: /home/csutter/DRIVE-clean/notebooks/plots_model_results.ipynb, where we ran it for the final model as well as for the CNN only. We did it this way in the paper so that final results would align in the text paragraphs in the paper. [ Different than how we have to do it for the + weather analysis ]

### Weather analyses/summaries

In [7]:
# Prep data


# --- Step 0: Data Preparation & Extracting True Class Probabilities ---

print(cnn.columns)
print(ds.columns)

# Helper functions to grab the probability of the true labeled class (img_cat)
def get_true_prob_cnn(row):
    col_name = f"prob_{row['img_cat']}"
    return row[col_name]

def get_true_prob_ds(row):
    col_name = f"ds_prob_{row['img_cat']}"
    return row[col_name]

# Apply the functions to create a standardized 'true_class_prob' column in both
cnn['true_class_prob'] = cnn.apply(get_true_prob_cnn, axis=1)
ds['true_class_prob'] = ds.apply(get_true_prob_ds, axis=1)

# Merge on unique identifiers, including 'img_cat' so it doesn't get duplicated
merged = cnn.merge(
    ds, 
    on=['img_orig', 'tracker', 'img_cat'], 
    how='inner', 
    suffixes=('_cnn', '_ds')
)

# Calculate the shift in true class probability (Positive = Weather data helped)
merged['true_prob_shift'] = merged['true_class_prob_ds'] - merged['true_class_prob_cnn']

Index(['index', 'Unnamed: 0.4', 'Unnamed: 0.3', 'Unnamed: 0.2', 'Unnamed: 0.1',
       'innerPhase', 'Unnamed: 0', 'outerPhase', 'img_name', 'img_orig',
       'site', 'img_index', 'img_cat', 'foldnum', 'ID', 'Latitude',
       'Longitude', 'date', 'yr', 'mo', 'day', 'time', 'yr_mo', 'timeofday',
       'timeofevent', 'innerPhaseOrig', 'prob_dry', 'prob_poor_viz',
       'prob_snow', 'prob_snow_severe', 'prob_wet', 'model_pred', 'tracker',
       'model_prob'],
      dtype='object')
Index(['index', 'Unnamed: 0.1', 'innerPhase', 'outerPhase', 'img_name',
       'img_orig', 'site', 'img_cat', 'foldnum', 'timeofday', 'timeofevent',
       'calib_prob_dry', 'calib_prob_poor_viz', 'calib_prob_snow',
       'calib_prob_snow_severe', 'calib_prob_wet', 'calib_prob', 'Unnamed: 0',
       'img_orig_hrrr', 'img_index', 'Latitude', 'Longitude', 'yr', 'mo',
       'day', 'date', 'time', 'ymd', 'date_and_time_str', 'date_and_time_dt',
       'date_and_time_dt_round', 'date_and_time_dt_init', 'init_hr',
       'init_year', 'init_month', 'init_day', 'init_yyyymmdd', 'hrrr_file',
       'HRRR_latlon', 'HRRR_distkm', 'time.1', 'valid_time', 'latitude',
       'longitude', 't2m', 'pt', 'sh2', 'd2m', 'r2', 'u10', 'v10', 'si10',
       'asnow', 'tp', 'orog', 'cape', 'mslma', 'dswrf', 'dlwrf', 'tcc', 'gh',
       'dpt', 'atmosphere', 'isobaricInhPa', 'uavg', 'ds_prob_dry',
       'ds_prob_poor_viz', 'ds_prob_snow', 'ds_prob_snow_severe',
       'ds_prob_wet', 'ds_pred', 'ds_prob', 'model_pred', 'tracker'],
      dtype='object')

index_cnn
Unnamed: 0.4
Unnamed: 0.3
Unnamed: 0.2
Unnamed: 0.1_cnn
innerPhase_cnn
Unnamed: 0_cnn
outerPhase_cnn
img_name_cnn
img_orig
site_cnn
img_index_cnn
img_cat
foldnum_cnn
ID
Latitude_cnn
Longitude_cnn
date_cnn
yr_cnn
mo_cnn
day_cnn
time_cnn
yr_mo
timeofday_cnn
timeofevent_cnn
innerPhaseOrig
prob_dry
prob_poor_viz
prob_snow
prob_snow_severe
prob_wet
model_pred_cnn
tracker
model_prob
true_class_prob_cnn
index_ds
Unnamed: 0.1_ds
innerPhase_ds
outerPhase_ds
img_name_ds
site_ds
foldnum_ds
timeofday_ds
timeofevent_ds
calib_prob_dry
calib_prob_poor_viz
calib_prob_snow
calib_prob_snow_severe
calib_prob_wet
calib_prob
Unnamed: 0_ds
img_orig_hrrr
img_index_ds
Latitude_ds
Longitude_ds
yr_ds
mo_ds
day_ds
date_ds
time_ds
ymd
date_and_time_str
date_and_time_dt
date_and_time_dt_round
date_and_time_dt_init
init_hr
init_year
init_month
init_day
init_yyyymmdd
hrrr_file
HRRR_latlon
HRRR_distkm
time.1
valid_time
latitude
longitude
t2m
pt
sh2
d2m
r2
u10
v10
si10
asnow
tp
orog
cape
mslma
dswrf
dlwrf
tcc
gh
dpt
atmosphere
isobaricInhPa
uavg
ds_prob_dry
ds_prob_poor_viz
ds_prob_snow
ds_prob_snow_severe
ds_prob_wet
ds_pred
ds_prob
model_pred_ds
true_class_prob_ds
true_prob_shift

In [54]:
print(len(mergedf))

107445

In [55]:
mergedf.head(4)

,index,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,innerPhase,Unnamed: 0,outerPhase,img_name,img_orig,site,img_index,img_cat,foldnum,ID,Latitude,Longitude,date,yr,mo,day,time,yr_mo,timeofday,timeofevent,innerPhaseOrig,prob_dry,prob_poor_viz,prob_snow,prob_snow_severe,prob_wet,model_pred,tracker,model_prob,ens_pred,ensembleAvg_dry,ensembleAvg_snow,ensembleAvg_snow_severe,ensembleAvg_wet,ensembleAvg_poor_viz,ens_prob
0,1774,1774,1774,1774,1774,NAOuterTest,1774,outerTest,"Routes_5,_8,_12_Burrstone_Road_Interchange___U...",/home/csutter/DRIVE/site_analysis/group_labeli...,Skyline_2103,613,wet,2,Skyline_2103,43.092303,-75.262824,1/24/22,2022,1,24,14:00:03,202201,day,"dawn:11:52:42.959980, sunrise:12:24:05.866980,...",NAOuterTest,0.183997,0.000286,0.004217,0.000651,0.810849,wet,OT2_m1_T3V4,0.810849,wet,0.47322,0.054477,0.001765,0.463822,0.006715,0.463822
1,1774,1774,1774,1774,1774,NAOuterTest,1774,outerTest,"Routes_5,_8,_12_Burrstone_Road_Interchange___U...",/home/csutter/DRIVE/site_analysis/group_labeli...,Skyline_2103,613,wet,2,Skyline_2103,43.092303,-75.262824,1/24/22,2022,1,24,14:00:03,202201,day,"dawn:11:52:42.959980, sunrise:12:24:05.866980,...",NAOuterTest,0.295133,0.001286,0.047939,0.001621,0.654021,wet,OT2_m0_T0V1,0.654021,wet,0.47322,0.054477,0.001765,0.463822,0.006715,0.463822
2,1774,1774,1774,1774,1774,NAOuterTest,1774,outerTest,"Routes_5,_8,_12_Burrstone_Road_Interchange___U...",/home/csutter/DRIVE/site_analysis/group_labeli...,Skyline_2103,613,wet,2,Skyline_2103,43.092303,-75.262824,1/24/22,2022,1,24,14:00:03,202201,day,"dawn:11:52:42.959980, sunrise:12:24:05.866980,...",NAOuterTest,0.237617,0.000894,0.023327,0.001704,0.736459,wet,OT2_m2_T4V5,0.736459,wet,0.47322,0.054477,0.001765,0.463822,0.006715,0.463822
3,1774,1774,1774,1774,1774,NAOuterTest,1774,outerTest,"Routes_5,_8,_12_Burrstone_Road_Interchange___U...",/home/csutter/DRIVE/site_analysis/group_labeli...,Skyline_2103,613,wet,2,Skyline_2103,43.092303,-75.262824,1/24/22,2022,1,24,14:00:03,202201,day,"dawn:11:52:42.959980, sunrise:12:24:05.866980,...",NAOuterTest,0.227574,0.001678,0.022478,0.001742,0.746528,wet,OT2_m3_T5V0,0.746528,wet,0.47322,0.054477,0.001765,0.463822,0.006715,0.463822

In [53]:



# --- Analysis 1: The Transition Matrix (Rescue vs. Ruin) ---
def determine_transition(row):
    cnn_correct = row['model_pred_cnn'] == row['img_cat']
    ens_correct = row['ens_pred'] == row['img_cat']
    
    if not cnn_correct and ens_correct:
        return '1_Rescued (CNN Wrong -> DS Right)'
    elif cnn_correct and not ens_correct:
        return '2_Ruined (CNN Right -> DS Wrong)'
    elif cnn_correct and ens_correct:
        return '3_Agreed (Correct)'
    else:
        return '4_Agreed (Incorrect)'

mergedf['transition_state'] = mergedf.apply(determine_transition, axis=1)

transition_summary = mergedf.groupby(['img_cat', 'transition_state']).size().unstack(fill_value=0)
if not transition_summary.empty:
    transition_summary['Total_Images'] = transition_summary.sum(axis=1)

print("--- Analysis 1: Transition Matrix (Rescue vs. Ruin) ---")
display(transition_summary)


# --- Analysis 2: The Confidence Shift (When Models Agree) ---
agreed_mask = mergedf['model_pred_cnn'] == mergedf['ens_pred']
agreed_df = mergedf[agreed_mask].copy()

# Shift in the probability of the *predicted* class
agreed_df['pred_prob_shift'] = agreed_df['ens_prob'] - agreed_df['model_prob']
agreed_df['is_correct'] = agreed_df['model_pred_cnn'] == agreed_df['img_cat']

confidence_summary = agreed_df.groupby(['img_cat', 'is_correct'])['pred_prob_shift'].agg(
    Avg_Pred_Prob_Change='mean', 
    Observation_Count='count'
).reset_index()

print("\n--- Analysis 2: Predicted Confidence Shift (When Models Agree) ---")
display(confidence_summary)


# --- Analysis 3: Meteorological Dominance (Ruin Patterns) ---
ruined_df = mergedf[mergedf['transition_state'] == '2_Ruined (CNN Right -> DS Wrong)']

if not ruined_df.empty:
    ruin_patterns = ruined_df.groupby(['img_cat', 'ens_pred']).size().reset_index(name='False_Prediction_Count')
    ruin_patterns = ruin_patterns.sort_values(by=['img_cat', 'False_Prediction_Count'], ascending=[True, False])
    
    print("\n--- Analysis 3: Ruin Patterns (What did the DS model guess instead?) ---")
    display(ruin_patterns)
else:
    print("\n--- Analysis 3: No 'Ruined' predictions found! ---")


# --- Analysis 4: True Class Probability Shift (The "Hidden Lift") ---
# This looks at how the probability of the *correct* answer changed, 
# grouped by category and how the models ultimately behaved.
true_prob_summary = mergedf.groupby(['img_cat', 'transition_state'])['true_prob_shift'].agg(
    Avg_True_Prob_Shift='mean',
    Median_True_Prob_Shift='median'
).reset_index()

# Pivot for easier reading: Rows = Categories, Columns = Transition States
true_prob_pivot = true_prob_summary.pivot(
    index='img_cat', 
    columns='transition_state', 
    values='Avg_True_Prob_Shift'
).fillna(0)

print("\n--- Analysis 4: Average Shift in True Class Probability ---")
print("(Positive numbers mean the DS model gave higher probability to the correct answer than the CNN did)")
display(true_prob_pivot)

# --- Analysis 5: Decisiveness Shift (The "Rescue" Margin) ---
# Isolate the cases where the CNN was wrong, but the weather data fixed it
rescued_df = mergedf[mergedf['transition_state'] == '1_Rescued (CNN Wrong -> DS Right)'].copy()

if not rescued_df.empty:
    # Calculate the difference between the DS model's confident correct guess 
    # and the CNN's confident incorrect guess
    rescued_df['winning_prob_diff'] = rescued_df['ens_prob'] - rescued_df['model_prob']
    
    # Group by the true road condition category
    rescue_margin_summary = rescued_df.groupby('img_cat')['winning_prob_diff'].agg(
        Avg_Winning_Prob_Diff='mean',
        Median_Winning_Prob_Diff='median',
        Min_Diff='min', # Shows cases where DS was less confident in the right answer than CNN was in the wrong one
        Max_Diff='max', # Shows massive jumps in confidence
        Rescue_Count='count'
    ).reset_index()
    
    print("\n--- Analysis 5: Decisiveness Shift (The 'Rescue' Margin) ---")
    print("(Positive numbers mean the DS model was MORE confident in the RIGHT answer than the CNN was in the WRONG answer)")
    display(rescue_margin_summary)
else:
    print("\n--- Analysis 5: No 'Rescued' predictions found to analyze! ---")

KeyError: 'model_pred_cnn'

In [19]:
import pandas as pd

# 1. Define Correctness for both models
merged['CNN_Correct'] = merged['model_pred_cnn'] == merged['img_cat']
merged['DS_Correct'] = merged['ds_pred'] == merged['img_cat']

# Map booleans to explicit strings so our matrix labels look clean
merged['CNN_Result'] = merged['CNN_Correct'].map({True: 'CNN: Correct', False: 'CNN: Incorrect'})
merged['DS_Result'] = merged['DS_Correct'].map({True: 'DS: Correct', False: 'DS: Incorrect'})

# Define the order for the rows and columns (standard confusion matrix layout)
row_order = ['CNN: Correct', 'CNN: Incorrect']
col_order = ['DS: Correct', 'DS: Incorrect']

# --- Matrix 1: Counts & Percentages ---
total_obs = len(merged)

def format_counts(x):
    cnt = len(x)
    pct = (cnt / total_obs) * 100
    return f"{cnt} ({pct:.1f}%)"

matrix_1 = merged.groupby(['CNN_Result', 'DS_Result']).apply(format_counts).unstack()
matrix_1 = matrix_1.reindex(index=row_order, columns=col_order)

print("=== Matrix 1: Total Observations & Percentages ===")
display(matrix_1)


# --- Matrix 2: Average Predicted Probabilities ---
def format_pred_probs(x):
    cnn_mean = x['model_prob'].mean()
    ds_mean = x['ds_prob'].mean()
    return f"CNN: {cnn_mean:.3f} | DS: {ds_mean:.3f}"

matrix_2 = merged.groupby(['CNN_Result', 'DS_Result']).apply(format_pred_probs).unstack()
matrix_2 = matrix_2.reindex(index=row_order, columns=col_order)

print("\n=== Matrix 2: Average Predicted Probabilities ===")
print("(The probability the model assigned to its CHOSEN answer)")
display(matrix_2)


# --- Matrix 3: Average Labeled (True Class) Probabilities ---
def format_true_probs(x):
    cnn_mean = x['true_class_prob_cnn'].mean()
    ds_mean = x['true_class_prob_ds'].mean()
    return f"CNN: {cnn_mean:.3f} | DS: {ds_mean:.3f}"

matrix_3 = merged.groupby(['CNN_Result', 'DS_Result']).apply(format_true_probs).unstack()
matrix_3 = matrix_3.reindex(index=row_order, columns=col_order)

print("\n=== Matrix 3: Average Labeled (True Class) Probabilities ===")
print("(The probability the model assigned to the CORRECT answer)")
display(matrix_3)

=== Matrix 1: Total Observations & Percentages ===

DS_Result         DS: Correct  DS: Incorrect
CNN_Result
CNN: Correct    68037 (63.3%)    6230 (5.8%)
CNN: Incorrect  18630 (17.3%)  14548 (13.5%)

=== Matrix 2: Average Predicted Probabilities ===
(The probability the model assigned to its CHOSEN answer)

DS_Result                  DS: Correct           DS: Incorrect
CNN_Result
CNN: Correct    CNN: 0.762 | DS: 0.845  CNN: 0.611 | DS: 0.570
CNN: Incorrect  CNN: 0.593 | DS: 0.687  CNN: 0.650 | DS: 0.639

=== Matrix 3: Average Labeled (True Class) Probabilities ===
(The probability the model assigned to the CORRECT answer)

DS_Result                  DS: Correct           DS: Incorrect
CNN_Result
CNN: Correct    CNN: 0.762 | DS: 0.845  CNN: 0.611 | DS: 0.304
CNN: Incorrect  CNN: 0.256 | DS: 0.687  CNN: 0.185 | DS: 0.223

In [24]:
import pandas as pd

# 1. Get the base counts for all 4 transition states grouped by img_cat
base_counts = merged.groupby(['img_cat', 'transition_state']).size().unstack(fill_value=0)

# Exact column names from our transition function
rescue_col = '1_Rescued (CNN Wrong -> DS Right)'
ruin_col = '2_Ruined (CNN Right -> DS Wrong)'

# 2. Calculate percentages
# Approach A: % of the ENTIRE class 
class_totals = base_counts.sum(axis=1)
rescue_pct_class = (base_counts[rescue_col] / class_totals) * 100
ruin_pct_class = (base_counts[ruin_col] / class_totals) * 100

# Approach B: % of CHANGES (Rescued + Ruined sum to 100%)
# This isolates just the times the downstream model overruled the CNN
changed_totals = base_counts[rescue_col] + base_counts[ruin_col]
rescue_pct_change = (base_counts[rescue_col] / changed_totals) * 100
ruin_pct_change = (base_counts[ruin_col] / changed_totals) * 100

# 3. Build the final summary dataframe
impact_matrix = pd.DataFrame({
    'Total Class Images': class_totals,
    'Rescued Count': base_counts[rescue_col],
    'Ruined Count': base_counts[ruin_col],
    '% of Class Rescued': rescue_pct_class.map('{:.1f}%'.format),
    '% of Class Ruined': ruin_pct_class.map('{:.1f}%'.format),
    'Change Win Rate (Rescued)': rescue_pct_change.map('{:.1f}%'.format),
    'Change Loss Rate (Ruined)': ruin_pct_change.map('{:.1f}%'.format)
})

print("=== Matrix 4: Rescued vs. Ruined Impact by Class ===")
display(impact_matrix)

=== Matrix 4: Rescued vs. Ruined Impact by Class ===

,Total Class Images,Rescued Count,Ruined Count,% of Class Rescued,% of Class Ruined,Change Win Rate (Rescued),Change Loss Rate (Ruined)
img_cat,,,,,,,
dry,38000,9659,1137,25.4%,3.0%,89.5%,10.5%
poor_viz,4575,216,470,4.7%,10.3%,31.5%,68.5%
snow,14945,2815,682,18.8%,4.6%,80.5%,19.5%
snow_severe,7635,632,434,8.3%,5.7%,59.3%,40.7%
wet,42290,5308,3507,12.6%,8.3%,60.2%,39.8%

In [29]:
import pandas as pd

# 1. Get the base counts for all 4 transition states grouped by img_cat
base_counts = merged.groupby(['img_cat', 'transition_state']).size().unstack(fill_value=0)

# Exact column names from our transition function
rescue_col = '1_Rescued (CNN Wrong -> DS Right)'
ruin_col = '2_Ruined (CNN Right -> DS Wrong)'

# 2. Calculate percentages
# Approach A: % of the ENTIRE class 
class_totals = base_counts.sum(axis=1)
rescue_pct_class = (base_counts[rescue_col] / class_totals) * 100
ruin_pct_class = (base_counts[ruin_col] / class_totals) * 100

# Approach B: % of CHANGES (Rescued + Ruined sum to 100%)
# This isolates just the times the downstream model overruled the CNN
changed_totals = base_counts[rescue_col] + base_counts[ruin_col]
rescue_pct_change = (base_counts[rescue_col] / changed_totals) * 100
ruin_pct_change = (base_counts[ruin_col] / changed_totals) * 100

# 3. Build the final summary dataframe
impact_matrix = pd.DataFrame({
    'Total Class Images': class_totals,
    'Rescued Count': base_counts[rescue_col],
    'Ruined Count': base_counts[ruin_col],
    '% of Class Rescued': rescue_pct_class.map('{:.1f}%'.format),
    '% of Class Ruined': ruin_pct_class.map('{:.1f}%'.format),
    'Change Win Rate (Rescued)': rescue_pct_change.map('{:.1f}%'.format),
    'Change Loss Rate (Ruined)': ruin_pct_change.map('{:.1f}%'.format)
})

print("=== Matrix 4: Rescued vs. Ruined Impact by Class ===")
display(impact_matrix)

=== Matrix 4: Rescued vs. Ruined Impact by Class ===

,Total Class Images,Rescued Count,Ruined Count,% of Class Rescued,% of Class Ruined,Change Win Rate (Rescued),Change Loss Rate (Ruined)
img_cat,,,,,,,
dry,38000,9787,1096,25.8%,2.9%,89.9%,10.1%
poor_viz,4575,378,478,8.3%,10.4%,44.2%,55.8%
snow,14945,2876,688,19.2%,4.6%,80.7%,19.3%
snow_severe,7635,656,430,8.6%,5.6%,60.4%,39.6%
wet,42290,5676,3586,13.4%,8.5%,61.3%,38.7%

# Do analyses from final ensemble prediction
- Justification : ensembling only affected it +1.2%. Cleaner just to compare CNN to Final throughout all aspects of the work. Rather than having to look at CNN vs Downstream Vs Final in order to map the results all the way through. It's just complicated for no particular reason, esp since we do ultimately want all the percentages reported to map through. Additinally, there were other steps in there like calibration, etc. Just keep it simple by doing CNN vs. Final
- So for each CNN observation (img_name | tracker, so 107k, due to nested approach), we map it to the Final observation (23k), meaning the same single obs will map to the 5 different obs from CNN

In [31]:
preds = ["/home/csutter/DRIVE-clean/ensembling/data_preds/modelFinal_OT0.csv",
"/home/csutter/DRIVE-clean/ensembling/data_preds/modelFinal_OT1.csv",
"/home/csutter/DRIVE-clean/ensembling/data_preds/modelFinal_OT2.csv",
"/home/csutter/DRIVE-clean/ensembling/data_preds/modelFinal_OT3.csv",
"/home/csutter/DRIVE-clean/ensembling/data_preds/modelFinal_OT4.csv",
"/home/csutter/DRIVE-clean/ensembling/data_preds/modelFinal_OT5.csv"
]

val_list = []

#RUN FOR CNN
for m in preds:
    m_df = pd.read_csv(m)
    # m_df = m_df[m_df["phase"] == phaseset] ### UPDATE!
    # print(m)
    # print(sum(m_df["flag_correct"]))
    val_list.append(m_df)


df_ensemble = pd.concat(val_list)
df_ensemble.reset_index(drop=True, inplace=True)

In [33]:
print(len(df_ensemble))

df_ensemble.head(4)

21489

,Unnamed: 0,index,Unnamed: 0.2,Unnamed: 0.1,m0_innerPhase,outerPhase,img_name,img_orig,site,img_cat,foldnum,timeofday,timeofevent,m0_calib_prob_dry,m0_calib_prob_poor_viz,m0_calib_prob_snow,m0_calib_prob_snow_severe,m0_calib_prob_wet,m0_calib_prob,img_orig_hrrr,img_index,Latitude,Longitude,yr,mo,day,date,time,ymd,date_and_time_str,date_and_time_dt,date_and_time_dt_round,date_and_time_dt_init,init_hr,init_year,init_month,init_day,init_yyyymmdd,hrrr_file,HRRR_latlon,HRRR_distkm,time.1,valid_time,latitude,longitude,t2m,pt,sh2,d2m,r2,u10,v10,si10,asnow,tp,orog,cape,mslma,dswrf,dlwrf,tcc,gh,dpt,atmosphere,isobaricInhPa,uavg,o_prob_dry,o_prob_poor_viz,o_prob_snow,o_prob_snow_severe,o_prob_wet,o_pred,o_prob,classifier_TF,classifier_01,o_prob_calib,m0_calib_pred,m1_calib_prob_dry,m1_calib_prob_poor_viz,m1_calib_prob_snow,m1_calib_prob_snow_severe,m1_calib_prob_wet,m1_calib_pred,m1_calib_prob,m2_calib_prob_dry,m2_calib_prob_poor_viz,m2_calib_prob_snow,m2_calib_prob_snow_severe,m2_calib_prob_wet,m2_calib_pred,m2_calib_prob,m3_calib_prob_dry,m3_calib_prob_poor_viz,m3_calib_prob_snow,m3_calib_prob_snow_severe,m3_calib_prob_wet,m3_calib_pred,m3_calib_prob,m4_calib_prob_dry,m4_calib_prob_poor_viz,m4_calib_prob_snow,m4_calib_prob_snow_severe,m4_calib_prob_wet,m4_calib_pred,m4_calib_prob,list_5preds,list_5probs,dict_catAsKeys_modelAsValues,dict_catAsKeys_countAsValues,dict_catAsKeys_probsAsValues,dict_mostConfident_singleModel,ensembleAvg_dry,ensembleAvg_snow,ensembleAvg_snow_severe,ensembleAvg_wet,ensembleAvg_poor_viz,ensembleAvg_pred,ensembleAvg_predprob,ensembleMode_pred,ensembleMaxConf_pred,methodalign_1_2,methodalign_1_3,methodalign_2_3,select,decision,select_correct,ok_select
0,0,16723,16723,16723,NAOuterTest,outerTest,390_at_Lyell_Ave__Unknown__Skyline_6117_2022-0...,/home/csutter/DRIVE/site_analysis/outsideFinal...,Skyline_6117,snow,0,night,"dawn:12:01:47.085163, sunrise:12:33:07.626434,...",0.034961,0.001952,0.827273,0.036460,0.099354,0.827273,/home/csutter/DRIVE/site_analysis/outsideFinal...,17716,43.1645,-77.683375,2022,1,25,20220125,00:00:10,20220125,00:00:10 20220125,2022-01-25 00:00:10,2022-01-25 00:00:00,2022-01-24 22:00:00,22,2022,1,24,20220124,/home/csutter/AI2ES/cleaned/HRRR/2022/01/20220...,"[43.16642726192929, -77.6681040222615]",1.260186,2022-01-24 22:00:00,2022-01-25 00:00:00,43.166427,-77.668104,263.8228,264.84235,0.00172,262.51434,82.9,-2.540636,0.959994,2.757503,0.009366,0.588,160.3884,0.0,100748.0,0.0,234.1,100.0,5259.7210,241.56229,0.0,500.0,2.715957,0.038349,0.002141,0.810533,0.039994,0.108983,snow,0.810533,True,1,0.827273,snow,0.010397,0.000000,0.888208,0.002007,0.099387,snow,0.888208,0.002403,0.000000,0.813725,0.120462,0.063409,snow,0.813725,0.025091,0.000000,0.798817,0.003876,0.172216,snow,0.798817,0.014845,0.000000,0.792453,0.045929,0.146773,snow,0.792453,"['snow', 'snow', 'snow', 'snow', 'snow']","[0.8272727272727273, 0.8882082695252682, 0.813...","{'snow': ['m0', 'm1', 'm2', 'm3', 'm4']}",{'snow': 5},{'snow': 0.824095177046018},{'snow': 0.8882082695252682},0.017540,0.824095,0.041747,0.116228,0.000390,snow,0.824095,snow,snow,True,True,True,snow,align_avg_mode,True,True
1,1,16724,16724,16724,NAOuterTest,outerTest,390_at_Lyell_Ave__Unknown__Skyline_6117_2022-0...,/home/csutter/DRIVE/site_analysis/outsideFinal...,Skyline_6117,snow,0,night,"dawn:12:01:47.085163, sunrise:12:33:07.626434,...",0.020566,0.000000,0.701258,0.020080,0.258097,0.701258,/home/csutter/DRIVE/site_analysis/outsideFinal...,17717,43.1645,-77.683375,2022,1,25,20220125,00:30:12,20220125,00:30:12 20220125,2022-01-25 00:30:12,2022-01-25 01:00:00,2022-01-24 23:00:00,23,2022,1,24,20220124,/home/csutter/AI2ES/cleaned/HRRR/2022/01/20220...,"[43.16642726192929, -77.6681040222615]",1.260186,2022-01-24 23:00:00,2022-01-25 01:00:00,43.166427,-77.668104,265.1895,266.17490,0.00192,263.93730,86.7,-2.041184,2.278474,3.555572,0.007699,0.490,160.3884,0.0,100725.0,0.0,265.2,100.0,5257.7085,241.87479,0.0,500.0,3.059065,0.025528,0.000000,0.629176,0.024925,0.320371,snow,0.629176,True,1,0.701258,snow,0.007903,0.000000,0.831984,0.013075,0.147038,snow,0.831984,0.009922,0.002072,0.789474,0.064233,0.134299,snow,0.789474,0.017489,0.000000,0.798817,0.003478,0.180216,snow,0.798817,0.014085,0.001911,0.259730,0.011116,0.713158,wet,0.713158,"['snow', 'snow', 'snow', 'snow', 'wet']","[0.7012578616352201, 0.8319838056680162, 0.789...","{'snow': ['m0', 'm1', 'm2', 'm3'], 'wet': ['m4']}","{'snow': 4, 'wet': 1}","{'snow': 0.7803829798902749, 'wet': 0.71315789...",{'snow': 0.8319838056680162},0.013993,0.676252,0.022396,0.286562,0.000797,snow,0.676252,snow,snow,True,True,True,snow,align_avg_mode,True,True
2,2,16725,16725,16725,NAOuterTest,outerTest,390_at_Lyell_Ave__Unknown__Skyline_6117_2022-0...,/home/csutter/DRIVE/site_analysis/outsideFinal...,Skyline_6117,snow,0,night,"dawn:12:01:47.085163, sunrise:12:33:07.626434,...",0.017977,0.000000,0.296005,0.019352,0.666667,0.666667,/home/csutter/DRIVE/site_analysis/outsideFinal...,17718,43.1645,-77.683375,2022,1,25,20220125,00:45:12,20220125,00:45:12 20220125,2022-01-25 00:45:12,2022-01-25 01:00:00,2022-01-24 23:00:00,23,2022,1,24,20220124,/home/csutter/AI2ES/cleaned/HRRR/2022/01/20220...,"[43.16642726192929, -77.6681040222615]",1.260186,2022-01-24 23:00:00,2022-01-25 01:00:00,43.166427,-77.668104,265.1895,266.17490,0.00192,263.93730,86.7,-2.041184,2.278474,3.555572,0.007699,0.490,160.3884,0.0,100725.0,0.0,265.2,100.0,5257.7085,241.87479,0.0,500.0,3.059065,0.024636,0.000000,0.405656,0.026520,0.543188,wet,0.543188,False,0,0.666667,wet,0.016393,0.000384,0.577206,0.005746,0.400270,snow,0.577206,0.005160,0.001019,0.735507,0.071900,0.186414,snow,0.735507,0.052956,0.004757,0.506623,0.015333,0.420331,snow,0.506623,0.018665,0.002597,0.223425,0.014961,0.740351,wet,0.740351,"['wet', 'snow', 'snow', 'snow', 'wet']","[0.6666666666666666, 0.5772058823529411, 0.735...","{'wet': ['m0', 'm4'], 'snow': ['m1', 'm2', 'm3']}","{'wet': 2, 'snow': 3}","{'wet': 0.7035087719298245, 'snow': 0.60644521...",{'wet': 0.7403508771929825},0.022230,0.467753,0.025458,0.482807,0.001752,wet,0.482807,snow,wet,False,True,False,wet,align_avg_maxConf,False,True
3,3,16726,16726,16726,NAOuterTest,outerTest,390_at_Lyell_Ave__Unknown__Skyline_6117_2022-0...,/home/csutter/DRIVE/site_analysis/outsideFinal...,Skyline_6117,snow,0,night,"dawn:12:01:47.085163, sunrise:12:33:07.626434,...",0.061273,0.002687,0.701258,0.067079,0.167703,0.701258,/home/csutter/DRIVE/site_analysis/outsideFinal...,17719,43.1645,-77.683375,2022,1,25,20220125,01:15:13,20220125,01:15:13 20220125,2022-01-25 01:15:13,2022-01-25 01:00:00,2022-01-24 23:00:00,23,2022,1,24,20220124,/home/csutter/AI2ES/cleaned/HRRR/2022/01/20220...,"[43.16642726192929, -77.6681040222615]",1.260186,2022-01-24 23:00:00,2022-01-25 01:00:00,43.166427,-77.668104,265.1895,266.17490,0.00192,263.93730,86.7,-2.041184,2.278474,3.555572,0.007699,0.490,160.3884,0.0,100725.0,0.0,265.2,100.0,5257.7085,241.87479,0.0,500.0,3.059065,0.065487,0.002872,0.680714,0.071692,0.179235,snow,0.680714,True,1,0.701258,snow,0.006152,0.000000,0.888208,0.006003,0.099636,snow,0.888208,0.002689,0.000000,0.881579,0.072408,0.043324,snow,0.881579,0.018510,0.000657,0.798817,0.006521,0.175496,snow,0.798817,0.014702,0.000000,0.625000,0.017040,0.343258,snow,0.625000,"['snow', 'snow', 'snow', 'snow', 'snow']","[0.7012578616352201, 0.8882082695252682, 0.881...","{'snow': ['m0', 'm1', 'm2', 'm3', 'm4']}",{'snow': 5},{'snow': 0.7789723293152493},{'snow': 0.8882082695252682},0.020665,0.778972,0.033810,0.165884,0.000669,snow,0.778972,snow,snow,True,True,True,snow,align_avg_mode,True,True

In [36]:
for i in df_ensemble.columns:
    print(i)

Unnamed: 0
index
Unnamed: 0.2
Unnamed: 0.1
m0_innerPhase
outerPhase
img_name
img_orig
site
img_cat
foldnum
timeofday
timeofevent
m0_calib_prob_dry
m0_calib_prob_poor_viz
m0_calib_prob_snow
m0_calib_prob_snow_severe
m0_calib_prob_wet
m0_calib_prob
img_orig_hrrr
img_index
Latitude
Longitude
yr
mo
day
date
time
ymd
date_and_time_str
date_and_time_dt
date_and_time_dt_round
date_and_time_dt_init
init_hr
init_year
init_month
init_day
init_yyyymmdd
hrrr_file
HRRR_latlon
HRRR_distkm
time.1
valid_time
latitude
longitude
t2m
pt
sh2
d2m
r2
u10
v10
si10
asnow
tp
orog
cape
mslma
dswrf
dlwrf
tcc
gh
dpt
atmosphere
isobaricInhPa
uavg
o_prob_dry
o_prob_poor_viz
o_prob_snow
o_prob_snow_severe
o_prob_wet
o_pred
o_prob
classifier_TF
classifier_01
o_prob_calib
m0_calib_pred
m1_calib_prob_dry
m1_calib_prob_poor_viz
m1_calib_prob_snow
m1_calib_prob_snow_severe
m1_calib_prob_wet
m1_calib_pred
m1_calib_prob
m2_calib_prob_dry
m2_calib_prob_poor_viz
m2_calib_prob_snow
m2_calib_prob_snow_severe
m2_calib_prob_wet
m2_calib_pred
m2_calib_prob
m3_calib_prob_dry
m3_calib_prob_poor_viz
m3_calib_prob_snow
m3_calib_prob_snow_severe
m3_calib_prob_wet
m3_calib_pred
m3_calib_prob
m4_calib_prob_dry
m4_calib_prob_poor_viz
m4_calib_prob_snow
m4_calib_prob_snow_severe
m4_calib_prob_wet
m4_calib_pred
m4_calib_prob
list_5preds
list_5probs
dict_catAsKeys_modelAsValues
dict_catAsKeys_countAsValues
dict_catAsKeys_probsAsValues
dict_mostConfident_singleModel
ensembleAvg_dry
ensembleAvg_snow
ensembleAvg_snow_severe
ensembleAvg_wet
ensembleAvg_poor_viz
ensembleAvg_pred
ensembleAvg_predprob
ensembleMode_pred
ensembleMaxConf_pred
methodalign_1_2
methodalign_1_3
methodalign_2_3
select
decision
select_correct
ok_select

In [40]:
ens = df_ensemble[["img_orig","img_cat","select","ensembleAvg_dry",
"ensembleAvg_snow",
"ensembleAvg_snow_severe",
"ensembleAvg_wet",
"ensembleAvg_poor_viz"]]

ens = ens.rename(columns = {"select":"ens_pred"})

def get_pred_prob_ens(row):
    col_name = f"ensembleAvg_{row['img_cat']}"
    return row[col_name]
ens['ens_prob'] = ens.apply(get_pred_prob_ens, axis=1)

print(len(ens))

21489

In [46]:
# Merge on unique identifiers, including 'img_cat' so it doesn't get duplicated
mergedf = cnn.merge(
    ens, 
    on=['img_orig', 'img_cat'], 
    how='inner', 
    suffixes=('_cnn', '_final')
)

In [47]:
print(len(mergedf))

107445

In [56]:
mergedf.columns

Index(['index', 'Unnamed: 0.4', 'Unnamed: 0.3', 'Unnamed: 0.2', 'Unnamed: 0.1',
       'innerPhase', 'Unnamed: 0', 'outerPhase', 'img_name', 'img_orig',
       'site', 'img_index', 'img_cat', 'foldnum', 'ID', 'Latitude',
       'Longitude', 'date', 'yr', 'mo', 'day', 'time', 'yr_mo', 'timeofday',
       'timeofevent', 'innerPhaseOrig', 'prob_dry', 'prob_poor_viz',
       'prob_snow', 'prob_snow_severe', 'prob_wet', 'model_pred', 'tracker',
       'model_prob', 'ens_pred', 'ensembleAvg_dry', 'ensembleAvg_snow',
       'ensembleAvg_snow_severe', 'ensembleAvg_wet', 'ensembleAvg_poor_viz',
       'ens_prob'],
      dtype='object')

In [48]:
mergedf.head(5)

,index,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,innerPhase,Unnamed: 0,outerPhase,img_name,img_orig,site,img_index,img_cat,foldnum,ID,Latitude,Longitude,date,yr,mo,day,time,yr_mo,timeofday,timeofevent,innerPhaseOrig,prob_dry,prob_poor_viz,prob_snow,prob_snow_severe,prob_wet,model_pred,tracker,model_prob,ens_pred,ensembleAvg_dry,ensembleAvg_snow,ensembleAvg_snow_severe,ensembleAvg_wet,ensembleAvg_poor_viz,ens_prob
0,1774,1774,1774,1774,1774,NAOuterTest,1774,outerTest,"Routes_5,_8,_12_Burrstone_Road_Interchange___U...",/home/csutter/DRIVE/site_analysis/group_labeli...,Skyline_2103,613,wet,2,Skyline_2103,43.092303,-75.262824,1/24/22,2022,1,24,14:00:03,202201,day,"dawn:11:52:42.959980, sunrise:12:24:05.866980,...",NAOuterTest,0.183997,0.000286,0.004217,0.000651,0.810849,wet,OT2_m1_T3V4,0.810849,wet,0.47322,0.054477,0.001765,0.463822,0.006715,0.463822
1,1774,1774,1774,1774,1774,NAOuterTest,1774,outerTest,"Routes_5,_8,_12_Burrstone_Road_Interchange___U...",/home/csutter/DRIVE/site_analysis/group_labeli...,Skyline_2103,613,wet,2,Skyline_2103,43.092303,-75.262824,1/24/22,2022,1,24,14:00:03,202201,day,"dawn:11:52:42.959980, sunrise:12:24:05.866980,...",NAOuterTest,0.295133,0.001286,0.047939,0.001621,0.654021,wet,OT2_m0_T0V1,0.654021,wet,0.47322,0.054477,0.001765,0.463822,0.006715,0.463822
2,1774,1774,1774,1774,1774,NAOuterTest,1774,outerTest,"Routes_5,_8,_12_Burrstone_Road_Interchange___U...",/home/csutter/DRIVE/site_analysis/group_labeli...,Skyline_2103,613,wet,2,Skyline_2103,43.092303,-75.262824,1/24/22,2022,1,24,14:00:03,202201,day,"dawn:11:52:42.959980, sunrise:12:24:05.866980,...",NAOuterTest,0.237617,0.000894,0.023327,0.001704,0.736459,wet,OT2_m2_T4V5,0.736459,wet,0.47322,0.054477,0.001765,0.463822,0.006715,0.463822
3,1774,1774,1774,1774,1774,NAOuterTest,1774,outerTest,"Routes_5,_8,_12_Burrstone_Road_Interchange___U...",/home/csutter/DRIVE/site_analysis/group_labeli...,Skyline_2103,613,wet,2,Skyline_2103,43.092303,-75.262824,1/24/22,2022,1,24,14:00:03,202201,day,"dawn:11:52:42.959980, sunrise:12:24:05.866980,...",NAOuterTest,0.227574,0.001678,0.022478,0.001742,0.746528,wet,OT2_m3_T5V0,0.746528,wet,0.47322,0.054477,0.001765,0.463822,0.006715,0.463822
4,1774,1774,1774,1774,1774,NAOuterTest,1774,outerTest,"Routes_5,_8,_12_Burrstone_Road_Interchange___U...",/home/csutter/DRIVE/site_analysis/group_labeli...,Skyline_2103,613,wet,2,Skyline_2103,43.092303,-75.262824,1/24/22,2022,1,24,14:00:03,202201,day,"dawn:11:52:42.959980, sunrise:12:24:05.866980,...",NAOuterTest,0.208765,0.000648,0.012890,0.001216,0.776481,wet,OT2_m4_T1V3,0.776481,wet,0.47322,0.054477,0.001765,0.463822,0.006715,0.463822

In [58]:
# --- Step 0: Data Preparation ---
# Assuming your merged dataframe is called 'df'
df_ot = mergedf.copy()

# Helper functions to grab the probability of the true labeled class
def get_true_prob_cnn(row):
    return row[f"prob_{row['img_cat']}"]

def get_true_prob_ens(row):
    return row[f"ensembleAvg_{row['img_cat']}"]

# Extract true class probabilities
df_ot['true_class_prob_cnn'] = df_ot.apply(get_true_prob_cnn, axis=1)
df_ot['true_class_prob_ens'] = df_ot.apply(get_true_prob_ens, axis=1)

# Define Correctness
df_ot['CNN_Correct'] = df_ot['model_pred'] == df_ot['img_cat']
df_ot['Ens_Correct'] = df_ot['ens_pred'] == df_ot['img_cat']

# Map booleans to explicit strings for matrix labels
df_ot['CNN_Result'] = df_ot['CNN_Correct'].map({True: 'CNN: Correct', False: 'CNN: Incorrect'})
df_ot['Ens_Result'] = df_ot['Ens_Correct'].map({True: 'Ens: Correct', False: 'Ens: Incorrect'})

row_order = ['CNN: Correct', 'CNN: Incorrect']
col_order = ['Ens: Correct', 'Ens: Incorrect']

# ==========================================
# MACRO-LEVEL SUMMARIES
# ==========================================

# --- Matrix 1: Counts & Percentages ---
total_obs = len(df_ot)

def format_counts(x):
    cnt = len(x)
    pct = (cnt / total_obs) * 100
    return f"{cnt} ({pct:.1f}%)"

matrix_1 = df_ot.groupby(['CNN_Result', 'Ens_Result']).apply(format_counts).unstack()
matrix_1 = matrix_1.reindex(index=row_order, columns=col_order)

print("=== Matrix 1: Total Observations & Percentages ===")
display(matrix_1)

# --- Matrix 2: Average Predicted Probabilities ---
def format_pred_probs(x):
    cnn_mean = x['model_prob'].mean()
    ens_mean = x['ens_prob'].mean()
    return f"CNN: {cnn_mean:.3f} | Ens: {ens_mean:.3f}"

matrix_2 = df_ot.groupby(['CNN_Result', 'Ens_Result']).apply(format_pred_probs).unstack()
matrix_2 = matrix_2.reindex(index=row_order, columns=col_order)

print("\n=== Matrix 2: Average Predicted Probabilities (Probability of the CHOSEN answer) ===")
display(matrix_2)

# --- Matrix 3: Average Labeled (True Class) Probabilities ---
def format_true_probs(x):
    cnn_mean = x['true_class_prob_cnn'].mean()
    ens_mean = x['true_class_prob_ens'].mean()
    return f"CNN: {cnn_mean:.3f} | Ens: {ens_mean:.3f}"

matrix_3 = df_ot.groupby(['CNN_Result', 'Ens_Result']).apply(format_true_probs).unstack()
matrix_3 = matrix_3.reindex(index=row_order, columns=col_order)

print("\n=== Matrix 3: Average True Class Probabilities (Probability of the CORRECT answer) ===")
display(matrix_3)


# ==========================================
# CLASS-LEVEL SUMMARIES
# ==========================================

# --- Determine Transition States ---
def determine_transition(row):
    if not row['CNN_Correct'] and row['Ens_Correct']:
        return '1_Rescued (CNN Wrong -> Ens Right)'
    elif row['CNN_Correct'] and not row['Ens_Correct']:
        return '2_Ruined (CNN Right -> Ens Wrong)'
    elif row['CNN_Correct'] and row['Ens_Correct']:
        return '3_Agreed (Correct)'
    else:
        return '4_Agreed (Incorrect)'

df_ot['transition_state'] = df_ot.apply(determine_transition, axis=1)

# --- Matrix 4: Rescued vs. Ruined Impact by Class ---
base_counts = df_ot.groupby(['img_cat', 'transition_state']).size().unstack(fill_value=0)
rescue_col = '1_Rescued (CNN Wrong -> Ens Right)'
ruin_col = '2_Ruined (CNN Right -> Ens Wrong)'

# Ensure columns exist even if there were 0 rescues or ruins
for col in [rescue_col, ruin_col]:
    if col not in base_counts.columns:
        base_counts[col] = 0

class_totals = base_counts.sum(axis=1)
changed_totals = base_counts[rescue_col] + base_counts[ruin_col]

# Avoid division by zero by replacing 0s with NaNs temporarily
changed_totals_safe = changed_totals.replace(0, np.nan)

rescue_pct_class = (base_counts[rescue_col] / class_totals) * 100
ruin_pct_class = (base_counts[ruin_col] / class_totals) * 100
rescue_pct_change = (base_counts[rescue_col] / changed_totals_safe) * 100
ruin_pct_change = (base_counts[ruin_col] / changed_totals_safe) * 100

impact_matrix = pd.DataFrame({
    'Total Class Images': class_totals,
    'Rescued Count': base_counts[rescue_col],
    'Ruined Count': base_counts[ruin_col],
    '% of Class Rescued': rescue_pct_class.map('{:.1f}%'.format),
    '% of Class Ruined': ruin_pct_class.map('{:.1f}%'.format),
    'Change Win Rate (Rescued)': rescue_pct_change.fillna(0).map('{:.1f}%'.format),
    'Change Loss Rate (Ruined)': ruin_pct_change.fillna(0).map('{:.1f}%'.format)
})

print("\n=== Matrix 4: Rescued vs. Ruined Impact by Class ===")
display(impact_matrix)


# ==========================================
# PROBABILITY SHIFT ANALYSES
# ==========================================

# --- Analysis: Confidence Shift (When Models Agree) ---
agreed_mask = df_ot['model_pred'] == df_ot['ens_pred']
agreed_df = df_ot[agreed_mask].copy()

# Shift in probability for the agreed-upon predicted class
agreed_df['pred_prob_shift'] = agreed_df['ens_prob'] - agreed_df['model_prob']
agreed_df['is_correct'] = agreed_df['model_pred'] == agreed_df['img_cat']

confidence_summary = agreed_df.groupby(['img_cat', 'is_correct'])['pred_prob_shift'].agg(
    Avg_Pred_Prob_Change='mean', 
    Observation_Count='count'
).reset_index()

print("\n--- Predicted Confidence Shift (When Models Agree) ---")
display(confidence_summary)

# --- Analysis: Decisiveness Shift (The "Rescue" Margin) ---
rescued_df = df_ot[df_ot['transition_state'] == rescue_col].copy()

if not rescued_df.empty:
    rescued_df['winning_prob_diff'] = rescued_df['ens_prob'] - rescued_df['model_prob']
    
    rescue_margin_summary = rescued_df.groupby('img_cat')['winning_prob_diff'].agg(
        Avg_Winning_Prob_Diff='mean',
        Min_Diff='min',
        Max_Diff='max',
        Rescue_Count='count'
    ).reset_index()
    
    print("\n--- Decisiveness Shift (The 'Rescue' Margin) ---")
    display(rescue_margin_summary)
else:
    print("\n--- No 'Rescued' predictions found to analyze! ---")

# --- Analysis: Average Shift in True Class Probability ---
df_ot['true_prob_shift'] = df_ot['true_class_prob_ens'] - df_ot['true_class_prob_cnn']

true_prob_summary = df_ot.groupby(['img_cat', 'transition_state'])['true_prob_shift'].agg(
    Avg_True_Prob_Shift='mean'
).reset_index()

true_prob_pivot = true_prob_summary.pivot(
    index='img_cat', 
    columns='transition_state', 
    values='Avg_True_Prob_Shift'
).fillna(0)

print("\n--- Average Shift in True Class Probability ---")
display(true_prob_pivot)

=== Matrix 1: Total Observations & Percentages ===

Ens_Result       Ens: Correct Ens: Incorrect
CNN_Result
CNN: Correct    67057 (62.4%)    6062 (5.6%)
CNN: Incorrect  20548 (19.1%)  13778 (12.8%)

=== Matrix 2: Average Predicted Probabilities (Probability of the CHOSEN answer) ===

Ens_Result                 Ens: Correct           Ens: Incorrect
CNN_Result
CNN: Correct    CNN: 0.765 | Ens: 0.855  CNN: 0.617 | Ens: 0.294
CNN: Incorrect  CNN: 0.598 | Ens: 0.726  CNN: 0.660 | Ens: 0.222

=== Matrix 3: Average True Class Probabilities (Probability of the CORRECT answer) ===

Ens_Result                 Ens: Correct           Ens: Incorrect
CNN_Result
CNN: Correct    CNN: 0.765 | Ens: 0.855  CNN: 0.617 | Ens: 0.294
CNN: Incorrect  CNN: 0.257 | Ens: 0.726  CNN: 0.181 | Ens: 0.222

=== Matrix 4: Rescued vs. Ruined Impact by Class ===

,Total Class Images,Rescued Count,Ruined Count,% of Class Rescued,% of Class Ruined,Change Win Rate (Rescued),Change Loss Rate (Ruined)
img_cat,,,,,,,
dry,38000,10394,1130,27.4%,3.0%,90.2%,9.8%
poor_viz,4575,419,336,9.2%,7.3%,55.5%,44.5%
snow,14945,3235,653,21.6%,4.4%,83.2%,16.8%
snow_severe,7635,690,362,9.0%,4.7%,65.6%,34.4%
wet,42290,5810,3581,13.7%,8.5%,61.9%,38.1%

--- Predicted Confidence Shift (When Models Agree) ---

       img_cat  is_correct  Avg_Pred_Prob_Change  Observation_Count
0          dry       False             -0.439097               2267
1          dry        True              0.149989              23861
2     poor_viz       False             -0.564295                501
3     poor_viz        True             -0.018639               3096
4         snow       False             -0.429442               2251
5         snow        True              0.032364               8280
6  snow_severe       False             -0.495059                815
7  snow_severe        True              0.032626               5530
8          wet       False             -0.474891               5294
9          wet        True              0.077866              26290

--- Decisiveness Shift (The 'Rescue' Margin) ---

       img_cat  Avg_Winning_Prob_Diff  Min_Diff  Max_Diff  Rescue_Count
0          dry               0.118546 -0.650831  0.698663         10394
1     poor_viz               0.134674 -0.654164  0.480957           419
2         snow               0.065004 -0.586947  0.529161          3235
3  snow_severe               0.092983 -0.568876  0.524012           690
4          wet               0.185867 -0.502214  0.636701          5810

--- Average Shift in True Class Probability ---

transition_state,1_Rescued (CNN Wrong -> Ens Right),2_Ruined (CNN Right -> Ens Wrong),3_Agreed (Correct),4_Agreed (Incorrect)
img_cat,,,,
dry,0.495953,-0.323637,0.149989,0.084238
poor_viz,0.404295,-0.421955,-0.018639,-0.019613
snow,0.373089,-0.337365,0.032364,0.088761
snow_severe,0.381207,-0.349340,0.032626,0.087602
wet,0.490917,-0.308322,0.077866,0.002724

In [ ]:
import pandas as pd

# 1. Get the base counts for all 4 transition states grouped by img_cat
base_counts = merged.groupby(['img_cat', 'transition_state']).size().unstack(fill_value=0)

# Exact column names from our transition function
rescue_col = '1_Rescued (CNN Wrong -> DS Right)'
ruin_col = '2_Ruined (CNN Right -> DS Wrong)'

# 2. Calculate percentages
# Approach A: % of the ENTIRE class 
class_totals = base_counts.sum(axis=1)
rescue_pct_class = (base_counts[rescue_col] / class_totals) * 100
ruin_pct_class = (base_counts[ruin_col] / class_totals) * 100

# Approach B: % of CHANGES (Rescued + Ruined sum to 100%)
# This isolates just the times the downstream model overruled the CNN
changed_totals = base_counts[rescue_col] + base_counts[ruin_col]
rescue_pct_change = (base_counts[rescue_col] / changed_totals) * 100
ruin_pct_change = (base_counts[ruin_col] / changed_totals) * 100

# 3. Build the final summary dataframe
impact_matrix = pd.DataFrame({
    'Total Class Images': class_totals,
    'Rescued Count': base_counts[rescue_col],
    'Ruined Count': base_counts[ruin_col],
    '% of Class Rescued': rescue_pct_class.map('{:.1f}%'.format),
    '% of Class Ruined': ruin_pct_class.map('{:.1f}%'.format),
    'Change Win Rate (Rescued)': rescue_pct_change.map('{:.1f}%'.format),
    'Change Loss Rate (Ruined)': ruin_pct_change.map('{:.1f}%'.format)
})

print("=== Matrix 4: Rescued vs. Ruined Impact by Class ===")
display(impact_matrix)